// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(ulife_libFFI)
import ulife_libFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_ulife_lib_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_ulife_lib_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureUlifeLibInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol ApiClientProtocol: AnyObject, Sendable {
    
    /**
     * 在指定帖子下发表新的评论
     */
    func addCommentToPost(postId: UInt64, content: String) async throws 
    
    /**
     * 新增课程表项（全校课程或个人自定义日程）
     */
    func addScheduleItem() async throws 
    
    func changePassword(oldPassword: String, newPassword: String) async throws 
    
    /**
     * 发布新帖子
     */
    func createPost(boardId: String, title: String, content: String, tags: [String], medias: [Media]?) async throws 
    
    /**
     * 删除指定评论（仅限管理员或评论作者本人）
     */
    func deleteComment(commentId: UInt64) async throws 
    
    /**
     * 删除帖子（仅限管理员或贴主）
     */
    func deletePost(postId: UInt64) async throws 
    
    /**
     * 删除课程表项
     */
    func deleteScheduleItem() async throws 
    
    func downloadFile(url: String) async throws  -> Data
    
    /**
     * 报名参加活动
     */
    func enrollActivity(activityId: UInt64, username: String, studentId: String, major: String) async throws 
    
    /**
     * 收藏活动
     */
    func favoriteActivity(activityId: UInt64) async throws 
    
    /**
     * 收藏帖子
     */
    func favouritePost(postId: UInt64) async throws 
    
    /**
     * 获取活动详情
     */
    func getActivityDetails(activityId: UInt64) async throws 
    
    func getCurrentUserProfile() async throws 
    
    /**
     * 获取指定帖子详情
     */
    func getPost(postId: UInt64) async throws 
    
    /**
     * 获取指定帖子评论列表
     */
    func getPostComments(postId: UInt64, page: UInt64, pageSize: UInt64) async throws 
    
    /**
     * 点赞评论
     */
    func likeComment(commentId: UInt64) async throws 
    
    /**
     * 点赞帖子
     */
    func likePost(postId: UInt64) async throws 
    
    /**
     * 获取活动列表
     */
    func listActivities(queryParams: ListActivitiesRequest) async throws 
    
    /**
     * 获取论坛版块列表
     */
    func listBoards() async throws 
    
    /**
     * 获取全校课程列表
     */
    func listCourses() async throws 
    
    func listMyActivities() async throws 
    
    /**
     * 获取帖子列表
     */
    func listPosts(params: ListPostsRequest) async throws 
    
    /**
     * 获取用户课程表项
     */
    func listScheduleItems(semesterId: String, week: UInt64?) async throws 
    
    /**
     * 获取学期列表
     */
    func listSemesters() async throws 
    
    func login(studentId: String, password: String) async throws 
    
    func logout() async throws 
    
    func register(studentId: String, password: String, name: String, college: String, major: String, phone: String) async throws  -> UInt64
    
    /**
     * 回复指定评论
     */
    func replyComment(postId: UInt64, commentId: UInt64, content: String) async throws 
    
    func report(targetType: TargetType, reason: String, description: String?) async throws 
    
    func unfavoriteActivity(activityId: UInt64) async throws 
    
    /**
     * 取消收藏帖子
     */
    func unfavouritePost(postId: UInt64) async throws 
    
    /**
     * 取消点赞评论
     */
    func unlikeComment(commentId: UInt64) async throws 
    
    /**
     * 取消点赞帖子
     */
    func unlikePost(postId: UInt64) async throws 
    
    /**
     * 取消报名活动
     */
    func unrollActivity(activityId: UInt64) async throws 
    
    func updateCurrentUserProfile() async throws 
    
    /**
     * 更新帖子
     */
    func updatePost(postId: UInt64, title: String?, content: String?, tags: [String]?, medias: [String]?) async throws 
    
    /**
     * 更新课程表项
     */
    func updateScheduleItem() async throws 
    
}
open class ApiClient: ApiClientProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_ulife_lib_fn_clone_apiclient(self.handle, $0) }
    }
public convenience init(baseUrl: String, cacheFolder: String, cacheSize: UInt64)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_ulife_lib_fn_constructor_apiclient_new(
        FfiConverterString.lower(baseUrl),
        FfiConverterString.lower(cacheFolder),
        FfiConverterUInt64.lower(cacheSize),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_ulife_lib_fn_free_apiclient(handle, $0) }
    }

    

    
    /**
     * 在指定帖子下发表新的评论
     */
open func addCommentToPost(postId: UInt64, content: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_add_comment_to_post(
                    self.uniffiCloneHandle(),
                    FfiConverterUInt64.lower(postId),FfiConverterString.lower(content)
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * 新增课程表项（全校课程或个人自定义日程）
     */
open func addScheduleItem()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_add_schedule_item(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
open func changePassword(oldPassword: String, newPassword: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_change_password(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(oldPassword),FfiConverterString.lower(newPassword)
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * 发布新帖子
     */
open func createPost(boardId: String, title: String, content: String, tags: [String], medias: [Media]?)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_create_post(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(boardId),FfiConverterString.lower(title),FfiConverterString.lower(content),FfiConverterSequenceString.lower(tags),FfiConverterOptionSequenceTypeMedia.lower(medias)
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * 删除指定评论（仅限管理员或评论作者本人）
     */
open func deleteComment(commentId: UInt64)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_delete_comment(
                    self.uniffiCloneHandle(),
                    FfiConverterUInt64.lower(commentId)
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * 删除帖子（仅限管理员或贴主）
     */
open func deletePost(postId: UInt64)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_delete_post(
                    self.uniffiCloneHandle(),
                    FfiConverterUInt64.lower(postId)
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * 删除课程表项
     */
open func deleteScheduleItem()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_delete_schedule_item(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
open func downloadFile(url: String)async throws  -> Data  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_download_file(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(url)
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_rust_buffer,
            completeFunc: ffi_ulife_lib_rust_future_complete_rust_buffer,
            freeFunc: ffi_ulife_lib_rust_future_free_rust_buffer,
            liftFunc: FfiConverterData.lift,
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * 报名参加活动
     */
open func enrollActivity(activityId: UInt64, username: String, studentId: String, major: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_enroll_activity(
                    self.uniffiCloneHandle(),
                    FfiConverterUInt64.lower(activityId),FfiConverterString.lower(username),FfiConverterString.lower(studentId),FfiConverterString.lower(major)
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * 收藏活动
     */
open func favoriteActivity(activityId: UInt64)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_favorite_activity(
                    self.uniffiCloneHandle(),
                    FfiConverterUInt64.lower(activityId)
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * 收藏帖子
     */
open func favouritePost(postId: UInt64)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_favourite_post(
                    self.uniffiCloneHandle(),
                    FfiConverterUInt64.lower(postId)
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * 获取活动详情
     */
open func getActivityDetails(activityId: UInt64)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_get_activity_details(
                    self.uniffiCloneHandle(),
                    FfiConverterUInt64.lower(activityId)
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
open func getCurrentUserProfile()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_get_current_user_profile(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * 获取指定帖子详情
     */
open func getPost(postId: UInt64)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_get_post(
                    self.uniffiCloneHandle(),
                    FfiConverterUInt64.lower(postId)
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * 获取指定帖子评论列表
     */
open func getPostComments(postId: UInt64, page: UInt64, pageSize: UInt64)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_get_post_comments(
                    self.uniffiCloneHandle(),
                    FfiConverterUInt64.lower(postId),FfiConverterUInt64.lower(page),FfiConverterUInt64.lower(pageSize)
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * 点赞评论
     */
open func likeComment(commentId: UInt64)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_like_comment(
                    self.uniffiCloneHandle(),
                    FfiConverterUInt64.lower(commentId)
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * 点赞帖子
     */
open func likePost(postId: UInt64)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_like_post(
                    self.uniffiCloneHandle(),
                    FfiConverterUInt64.lower(postId)
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * 获取活动列表
     */
open func listActivities(queryParams: ListActivitiesRequest)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_list_activities(
                    self.uniffiCloneHandle(),
                    FfiConverterTypeListActivitiesRequest_lower(queryParams)
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * 获取论坛版块列表
     */
open func listBoards()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_list_boards(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * 获取全校课程列表
     */
open func listCourses()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_list_courses(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
open func listMyActivities()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_list_my_activities(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * 获取帖子列表
     */
open func listPosts(params: ListPostsRequest)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_list_posts(
                    self.uniffiCloneHandle(),
                    FfiConverterTypeListPostsRequest_lower(params)
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * 获取用户课程表项
     */
open func listScheduleItems(semesterId: String, week: UInt64?)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_list_schedule_items(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(semesterId),FfiConverterOptionUInt64.lower(week)
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * 获取学期列表
     */
open func listSemesters()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_list_semesters(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
open func login(studentId: String, password: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_login(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(studentId),FfiConverterString.lower(password)
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
open func logout()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_logout(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
open func register(studentId: String, password: String, name: String, college: String, major: String, phone: String)async throws  -> UInt64  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_register(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(studentId),FfiConverterString.lower(password),FfiConverterString.lower(name),FfiConverterString.lower(college),FfiConverterString.lower(major),FfiConverterString.lower(phone)
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_u64,
            completeFunc: ffi_ulife_lib_rust_future_complete_u64,
            freeFunc: ffi_ulife_lib_rust_future_free_u64,
            liftFunc: FfiConverterUInt64.lift,
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * 回复指定评论
     */
open func replyComment(postId: UInt64, commentId: UInt64, content: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_reply_comment(
                    self.uniffiCloneHandle(),
                    FfiConverterUInt64.lower(postId),FfiConverterUInt64.lower(commentId),FfiConverterString.lower(content)
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
open func report(targetType: TargetType, reason: String, description: String?)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_report(
                    self.uniffiCloneHandle(),
                    FfiConverterTypeTargetType_lower(targetType),FfiConverterString.lower(reason),FfiConverterOptionString.lower(description)
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
open func unfavoriteActivity(activityId: UInt64)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_unfavorite_activity(
                    self.uniffiCloneHandle(),
                    FfiConverterUInt64.lower(activityId)
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * 取消收藏帖子
     */
open func unfavouritePost(postId: UInt64)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_unfavourite_post(
                    self.uniffiCloneHandle(),
                    FfiConverterUInt64.lower(postId)
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * 取消点赞评论
     */
open func unlikeComment(commentId: UInt64)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_unlike_comment(
                    self.uniffiCloneHandle(),
                    FfiConverterUInt64.lower(commentId)
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * 取消点赞帖子
     */
open func unlikePost(postId: UInt64)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_unlike_post(
                    self.uniffiCloneHandle(),
                    FfiConverterUInt64.lower(postId)
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * 取消报名活动
     */
open func unrollActivity(activityId: UInt64)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_unroll_activity(
                    self.uniffiCloneHandle(),
                    FfiConverterUInt64.lower(activityId)
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
open func updateCurrentUserProfile()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_update_current_user_profile(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * 更新帖子
     */
open func updatePost(postId: UInt64, title: String?, content: String?, tags: [String]?, medias: [String]?)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_update_post(
                    self.uniffiCloneHandle(),
                    FfiConverterUInt64.lower(postId),FfiConverterOptionString.lower(title),FfiConverterOptionString.lower(content),FfiConverterOptionSequenceString.lower(tags),FfiConverterOptionSequenceString.lower(medias)
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    
    /**
     * 更新课程表项
     */
open func updateScheduleItem()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_apiclient_update_schedule_item(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeApiClient: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = ApiClient

    public static func lift(_ handle: UInt64) throws -> ApiClient {
        return ApiClient(unsafeFromHandle: handle)
    }

    public static func lower(_ value: ApiClient) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ApiClient {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: ApiClient, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeApiClient_lift(_ handle: UInt64) throws -> ApiClient {
    return try FfiConverterTypeApiClient.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeApiClient_lower(_ value: ApiClient) -> UInt64 {
    return FfiConverterTypeApiClient.lower(value)
}






public protocol PersistenceManagerProtocol: AnyObject, Sendable {
    
    func getCurrentUserToken() throws  -> String?
    
    func saveCurrentUser(currentUser: CurrentUser) async throws 
    
}
open class PersistenceManager: PersistenceManagerProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_ulife_lib_fn_clone_persistencemanager(self.handle, $0) }
    }
    /**
     * 创建 PersistenceManager 实例
     */
public convenience init(baseFolder: String)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_ulife_lib_fn_constructor_persistencemanager_new(
        FfiConverterString.lower(baseFolder),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_ulife_lib_fn_free_persistencemanager(handle, $0) }
    }

    

    
open func getCurrentUserToken()throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_ulife_lib_fn_method_persistencemanager_get_current_user_token(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func saveCurrentUser(currentUser: CurrentUser)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_ulife_lib_fn_method_persistencemanager_save_current_user(
                    self.uniffiCloneHandle(),
                    FfiConverterTypeCurrentUser_lower(currentUser)
                )
            },
            pollFunc: ffi_ulife_lib_rust_future_poll_void,
            completeFunc: ffi_ulife_lib_rust_future_complete_void,
            freeFunc: ffi_ulife_lib_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeError_lift
        )
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePersistenceManager: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = PersistenceManager

    public static func lift(_ handle: UInt64) throws -> PersistenceManager {
        return PersistenceManager(unsafeFromHandle: handle)
    }

    public static func lower(_ value: PersistenceManager) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PersistenceManager {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: PersistenceManager, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePersistenceManager_lift(_ handle: UInt64) throws -> PersistenceManager {
    return try FfiConverterTypePersistenceManager.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePersistenceManager_lower(_ value: PersistenceManager) -> UInt64 {
    return FfiConverterTypePersistenceManager.lower(value)
}




public struct CurrentUser: Equatable, Hashable {
    public var token: String
    public var user: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(token: String, user: String) {
        self.token = token
        self.user = user
    }

    
}

#if compiler(>=6)
extension CurrentUser: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCurrentUser: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CurrentUser {
        return
            try CurrentUser(
                token: FfiConverterString.read(from: &buf), 
                user: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: CurrentUser, into buf: inout [UInt8]) {
        FfiConverterString.write(value.token, into: &buf)
        FfiConverterString.write(value.user, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCurrentUser_lift(_ buf: RustBuffer) throws -> CurrentUser {
    return try FfiConverterTypeCurrentUser.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCurrentUser_lower(_ value: CurrentUser) -> RustBuffer {
    return FfiConverterTypeCurrentUser.lower(value)
}


public struct ListActivitiesRequest: Equatable, Hashable {
    public var page: UInt64
    public var pageSize: UInt64
    public var keyword: String?
    public var activityType: UInt8?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(page: UInt64, pageSize: UInt64, keyword: String?, activityType: UInt8?) {
        self.page = page
        self.pageSize = pageSize
        self.keyword = keyword
        self.activityType = activityType
    }

    
}

#if compiler(>=6)
extension ListActivitiesRequest: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeListActivitiesRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ListActivitiesRequest {
        return
            try ListActivitiesRequest(
                page: FfiConverterUInt64.read(from: &buf), 
                pageSize: FfiConverterUInt64.read(from: &buf), 
                keyword: FfiConverterOptionString.read(from: &buf), 
                activityType: FfiConverterOptionUInt8.read(from: &buf)
        )
    }

    public static func write(_ value: ListActivitiesRequest, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.page, into: &buf)
        FfiConverterUInt64.write(value.pageSize, into: &buf)
        FfiConverterOptionString.write(value.keyword, into: &buf)
        FfiConverterOptionUInt8.write(value.activityType, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeListActivitiesRequest_lift(_ buf: RustBuffer) throws -> ListActivitiesRequest {
    return try FfiConverterTypeListActivitiesRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeListActivitiesRequest_lower(_ value: ListActivitiesRequest) -> RustBuffer {
    return FfiConverterTypeListActivitiesRequest.lower(value)
}


public struct ListPostsRequest: Equatable, Hashable {
    public var page: UInt64
    public var pageSize: UInt64
    public var boardId: String?
    public var filter: [String]?
    public var sort: [String]?
    public var keyword: [String]?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(page: UInt64, pageSize: UInt64, boardId: String?, filter: [String]?, sort: [String]?, keyword: [String]?) {
        self.page = page
        self.pageSize = pageSize
        self.boardId = boardId
        self.filter = filter
        self.sort = sort
        self.keyword = keyword
    }

    
}

#if compiler(>=6)
extension ListPostsRequest: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeListPostsRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ListPostsRequest {
        return
            try ListPostsRequest(
                page: FfiConverterUInt64.read(from: &buf), 
                pageSize: FfiConverterUInt64.read(from: &buf), 
                boardId: FfiConverterOptionString.read(from: &buf), 
                filter: FfiConverterOptionSequenceString.read(from: &buf), 
                sort: FfiConverterOptionSequenceString.read(from: &buf), 
                keyword: FfiConverterOptionSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: ListPostsRequest, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.page, into: &buf)
        FfiConverterUInt64.write(value.pageSize, into: &buf)
        FfiConverterOptionString.write(value.boardId, into: &buf)
        FfiConverterOptionSequenceString.write(value.filter, into: &buf)
        FfiConverterOptionSequenceString.write(value.sort, into: &buf)
        FfiConverterOptionSequenceString.write(value.keyword, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeListPostsRequest_lift(_ buf: RustBuffer) throws -> ListPostsRequest {
    return try FfiConverterTypeListPostsRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeListPostsRequest_lower(_ value: ListPostsRequest) -> RustBuffer {
    return FfiConverterTypeListPostsRequest.lower(value)
}


public struct Media: Equatable, Hashable {
    public var mediaType: String
    public var url: String
    public var thumbnailUrl: String
    public var meta: MediaMeta

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(mediaType: String, url: String, thumbnailUrl: String, meta: MediaMeta) {
        self.mediaType = mediaType
        self.url = url
        self.thumbnailUrl = thumbnailUrl
        self.meta = meta
    }

    
}

#if compiler(>=6)
extension Media: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMedia: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Media {
        return
            try Media(
                mediaType: FfiConverterString.read(from: &buf), 
                url: FfiConverterString.read(from: &buf), 
                thumbnailUrl: FfiConverterString.read(from: &buf), 
                meta: FfiConverterTypeMediaMeta.read(from: &buf)
        )
    }

    public static func write(_ value: Media, into buf: inout [UInt8]) {
        FfiConverterString.write(value.mediaType, into: &buf)
        FfiConverterString.write(value.url, into: &buf)
        FfiConverterString.write(value.thumbnailUrl, into: &buf)
        FfiConverterTypeMediaMeta.write(value.meta, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMedia_lift(_ buf: RustBuffer) throws -> Media {
    return try FfiConverterTypeMedia.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMedia_lower(_ value: Media) -> RustBuffer {
    return FfiConverterTypeMedia.lower(value)
}


public struct MediaMeta: Equatable, Hashable {
    public var size: UInt64
    public var width: UInt64?
    public var height: UInt64?
    public var filename: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(size: UInt64, width: UInt64?, height: UInt64?, filename: String) {
        self.size = size
        self.width = width
        self.height = height
        self.filename = filename
    }

    
}

#if compiler(>=6)
extension MediaMeta: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMediaMeta: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MediaMeta {
        return
            try MediaMeta(
                size: FfiConverterUInt64.read(from: &buf), 
                width: FfiConverterOptionUInt64.read(from: &buf), 
                height: FfiConverterOptionUInt64.read(from: &buf), 
                filename: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: MediaMeta, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.size, into: &buf)
        FfiConverterOptionUInt64.write(value.width, into: &buf)
        FfiConverterOptionUInt64.write(value.height, into: &buf)
        FfiConverterString.write(value.filename, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMediaMeta_lift(_ buf: RustBuffer) throws -> MediaMeta {
    return try FfiConverterTypeMediaMeta.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMediaMeta_lower(_ value: MediaMeta) -> RustBuffer {
    return FfiConverterTypeMediaMeta.lower(value)
}


public struct Test: Equatable, Hashable {
    public var id: Int32
    public var name: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: Int32, name: String) {
        self.id = id
        self.name = name
    }

    
}

#if compiler(>=6)
extension Test: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Test {
        return
            try Test(
                id: FfiConverterInt32.read(from: &buf), 
                name: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Test, into buf: inout [UInt8]) {
        FfiConverterInt32.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTest_lift(_ buf: RustBuffer) throws -> Test {
    return try FfiConverterTypeTest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTest_lower(_ value: Test) -> RustBuffer {
    return FfiConverterTypeTest.lower(value)
}


public enum Error: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case IoError(message: String)
    
    case ReqwestError(message: String)
    
    case ProstDecodeError(message: String)
    
    case ProstEncodeError(message: String)
    
    case CacheSerdeError(message: String)
    
    case Uninitialized(message: String)
    
    case UnknownError(message: String)
    
    case HttpError(message: String)
    
    case UnAuthorized(message: String)
    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension Error: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeError: FfiConverterRustBuffer {
    typealias SwiftType = Error

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Error {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .IoError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .ReqwestError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .ProstDecodeError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .ProstEncodeError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .CacheSerdeError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .Uninitialized(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .UnknownError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 8: return .HttpError(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 9: return .UnAuthorized(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Error, into buf: inout [UInt8]) {
        switch value {

        

        
        case .IoError(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .ReqwestError(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .ProstDecodeError(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .ProstEncodeError(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .CacheSerdeError(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .Uninitialized(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))
        case .UnknownError(_ /* message is ignored*/):
            writeInt(&buf, Int32(7))
        case .HttpError(_ /* message is ignored*/):
            writeInt(&buf, Int32(8))
        case .UnAuthorized(_ /* message is ignored*/):
            writeInt(&buf, Int32(9))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeError_lift(_ buf: RustBuffer) throws -> Error {
    return try FfiConverterTypeError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeError_lower(_ value: Error) -> RustBuffer {
    return FfiConverterTypeError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum TargetType: Equatable, Hashable {
    
    case post(postId: UInt64
    )
    case comment(commentId: UInt64
    )



}

#if compiler(>=6)
extension TargetType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTargetType: FfiConverterRustBuffer {
    typealias SwiftType = TargetType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TargetType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .post(postId: try FfiConverterUInt64.read(from: &buf)
        )
        
        case 2: return .comment(commentId: try FfiConverterUInt64.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: TargetType, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .post(postId):
            writeInt(&buf, Int32(1))
            FfiConverterUInt64.write(postId, into: &buf)
            
        
        case let .comment(commentId):
            writeInt(&buf, Int32(2))
            FfiConverterUInt64.write(commentId, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTargetType_lift(_ buf: RustBuffer) throws -> TargetType {
    return try FfiConverterTypeTargetType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTargetType_lower(_ value: TargetType) -> RustBuffer {
    return FfiConverterTypeTargetType.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt8: FfiConverterRustBuffer {
    typealias SwiftType = UInt8?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt8.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt8.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionSequenceTypeMedia: FfiConverterRustBuffer {
    typealias SwiftType = [Media]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceTypeMedia.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceTypeMedia.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMedia: FfiConverterRustBuffer {
    typealias SwiftType = [Media]

    public static func write(_ value: [Media], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMedia.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Media] {
        let len: Int32 = try readInt(&buf)
        var seq = [Media]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMedia.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureUlifeLibInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_ulife_lib_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_add_comment_to_post() != 23023) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_add_schedule_item() != 56330) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_change_password() != 29182) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_create_post() != 53557) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_delete_comment() != 3770) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_delete_post() != 26443) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_delete_schedule_item() != 27052) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_download_file() != 53861) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_enroll_activity() != 7237) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_favorite_activity() != 29014) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_favourite_post() != 59787) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_get_activity_details() != 50179) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_get_current_user_profile() != 44270) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_get_post() != 19563) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_get_post_comments() != 38060) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_like_comment() != 4853) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_like_post() != 65362) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_list_activities() != 6429) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_list_boards() != 26546) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_list_courses() != 41677) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_list_my_activities() != 17154) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_list_posts() != 29002) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_list_schedule_items() != 31759) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_list_semesters() != 13047) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_login() != 5020) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_logout() != 14878) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_register() != 4131) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_reply_comment() != 44830) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_report() != 8595) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_unfavorite_activity() != 29878) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_unfavourite_post() != 59842) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_unlike_comment() != 15734) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_unlike_post() != 38767) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_unroll_activity() != 18375) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_update_current_user_profile() != 29257) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_update_post() != 58214) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_apiclient_update_schedule_item() != 13287) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_persistencemanager_get_current_user_token() != 61292) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_method_persistencemanager_save_current_user() != 20524) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_constructor_apiclient_new() != 13980) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_ulife_lib_checksum_constructor_persistencemanager_new() != 46732) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureUlifeLibInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all