// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Protocol/activity.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// 活动状态枚举
enum Campus_Activity_ActivityStatus: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unspecified // = 0

  /// 进行中
  case ongoing // = 1

  /// 已结束
  case ended // = 2

  /// 已撤销
  case cancelled // = 3
  case UNRECOGNIZED(Int)

  init() {
    self = .unspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .ongoing
    case 2: self = .ended
    case 3: self = .cancelled
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .ongoing: return 1
    case .ended: return 2
    case .cancelled: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Campus_Activity_ActivityStatus] = [
    .unspecified,
    .ongoing,
    .ended,
    .cancelled,
  ]

}

/// 活动类型枚举
enum Campus_Activity_ActivityType: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case unspecified // = 0

  /// 讲座
  case lecture // = 1

  /// 社团
  case club // = 2

  /// 竞赛
  case competition // = 3
  case UNRECOGNIZED(Int)

  init() {
    self = .unspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .lecture
    case 2: self = .club
    case 3: self = .competition
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .lecture: return 1
    case .club: return 2
    case .competition: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Campus_Activity_ActivityType] = [
    .unspecified,
    .lecture,
    .club,
    .competition,
  ]

}

/// 分页信息
struct Campus_Activity_Pagination: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var total: Int64 = 0

  var page: Int32 = 0

  var pageSize: Int32 = 0

  var pages: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// 活动列表项（精简信息）
struct Campus_Activity_ActivityListItem: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: String = String()

  var title: String = String()

  var coverURL: String = String()

  var location: String = String()

  /// ISO8601 格式
  var startTime: String = String()

  var quota: Int32 = 0

  var currentEnrollments: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// 完整活动信息
struct Campus_Activity_Activity: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: String = String()

  var title: String = String()

  var content: String = String()

  var coverURL: String = String()

  var activityType: Campus_Activity_ActivityType = .unspecified

  var location: String = String()

  var organizer: String = String()

  /// ISO8601 格式
  var startTime: String = String()

  /// ISO8601 格式
  var endTime: String = String()

  var quota: Int32 = 0

  var currentEnrollments: Int32 = 0

  var needSignIn: Bool = false

  var status: Campus_Activity_ActivityStatus = .unspecified

  /// ISO8601 格式
  var createdAt: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// 活动详情（包含用户交互状态）
struct Campus_Activity_ActivityDetail: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var activity: Campus_Activity_Activity {
    get {return _activity ?? Campus_Activity_Activity()}
    set {_activity = newValue}
  }
  /// Returns true if `activity` has been explicitly set.
  var hasActivity: Bool {return self._activity != nil}
  /// Clears the value of `activity`. Subsequent reads from it will return its default value.
  mutating func clearActivity() {self._activity = nil}

  var isEnrolled: Bool = false

  var isCollected: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _activity: Campus_Activity_Activity? = nil
}

/// 报名记录
struct Campus_Activity_EnrollmentRecord: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var userID: String = String()

  var userName: String = String()

  var studentID: String = String()

  var major: String = String()

  var phoneNumber: String = String()

  var activityID: String = String()

  /// ISO8601 格式
  var enrollTime: String = String()

  /// 1:已报名, 2:已取消
  var attendanceStatus: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// 我的报名活动
struct Campus_Activity_MyEnrollmentItem: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var activityID: String = String()

  var title: String = String()

  var coverURL: String = String()

  var startTime: String = String()

  var endTime: String = String()

  /// 1:已报名, 2:已取消
  var myStatus: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// 我的收藏活动
struct Campus_Activity_MyCollectionItem: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var activityID: String = String()

  var title: String = String()

  var coverURL: String = String()

  var startTime: String = String()

  var endTime: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// 获取活动列表请求
struct Campus_Activity_GetActivitiesRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var keyword: String {
    get {return _keyword ?? String()}
    set {_keyword = newValue}
  }
  /// Returns true if `keyword` has been explicitly set.
  var hasKeyword: Bool {return self._keyword != nil}
  /// Clears the value of `keyword`. Subsequent reads from it will return its default value.
  mutating func clearKeyword() {self._keyword = nil}

  var activityType: Campus_Activity_ActivityType {
    get {return _activityType ?? .unspecified}
    set {_activityType = newValue}
  }
  /// Returns true if `activityType` has been explicitly set.
  var hasActivityType: Bool {return self._activityType != nil}
  /// Clears the value of `activityType`. Subsequent reads from it will return its default value.
  mutating func clearActivityType() {self._activityType = nil}

  var page: Int32 = 0

  var pageSize: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _keyword: String? = nil
  fileprivate var _activityType: Campus_Activity_ActivityType? = nil
}

/// 创建活动请求
struct Campus_Activity_CreateActivityRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var title: String = String()

  var content: String = String()

  var location: String = String()

  var organizer: String = String()

  var startTime: String = String()

  var endTime: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// 更新活动请求
struct Campus_Activity_UpdateActivityRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var title: String {
    get {return _title ?? String()}
    set {_title = newValue}
  }
  /// Returns true if `title` has been explicitly set.
  var hasTitle: Bool {return self._title != nil}
  /// Clears the value of `title`. Subsequent reads from it will return its default value.
  mutating func clearTitle() {self._title = nil}

  var content: String {
    get {return _content ?? String()}
    set {_content = newValue}
  }
  /// Returns true if `content` has been explicitly set.
  var hasContent: Bool {return self._content != nil}
  /// Clears the value of `content`. Subsequent reads from it will return its default value.
  mutating func clearContent() {self._content = nil}

  var coverURL: String {
    get {return _coverURL ?? String()}
    set {_coverURL = newValue}
  }
  /// Returns true if `coverURL` has been explicitly set.
  var hasCoverURL: Bool {return self._coverURL != nil}
  /// Clears the value of `coverURL`. Subsequent reads from it will return its default value.
  mutating func clearCoverURL() {self._coverURL = nil}

  var activityType: Campus_Activity_ActivityType {
    get {return _activityType ?? .unspecified}
    set {_activityType = newValue}
  }
  /// Returns true if `activityType` has been explicitly set.
  var hasActivityType: Bool {return self._activityType != nil}
  /// Clears the value of `activityType`. Subsequent reads from it will return its default value.
  mutating func clearActivityType() {self._activityType = nil}

  var location: String {
    get {return _location ?? String()}
    set {_location = newValue}
  }
  /// Returns true if `location` has been explicitly set.
  var hasLocation: Bool {return self._location != nil}
  /// Clears the value of `location`. Subsequent reads from it will return its default value.
  mutating func clearLocation() {self._location = nil}

  var organizer: String {
    get {return _organizer ?? String()}
    set {_organizer = newValue}
  }
  /// Returns true if `organizer` has been explicitly set.
  var hasOrganizer: Bool {return self._organizer != nil}
  /// Clears the value of `organizer`. Subsequent reads from it will return its default value.
  mutating func clearOrganizer() {self._organizer = nil}

  var startTime: String {
    get {return _startTime ?? String()}
    set {_startTime = newValue}
  }
  /// Returns true if `startTime` has been explicitly set.
  var hasStartTime: Bool {return self._startTime != nil}
  /// Clears the value of `startTime`. Subsequent reads from it will return its default value.
  mutating func clearStartTime() {self._startTime = nil}

  var endTime: String {
    get {return _endTime ?? String()}
    set {_endTime = newValue}
  }
  /// Returns true if `endTime` has been explicitly set.
  var hasEndTime: Bool {return self._endTime != nil}
  /// Clears the value of `endTime`. Subsequent reads from it will return its default value.
  mutating func clearEndTime() {self._endTime = nil}

  var quota: Int32 {
    get {return _quota ?? 0}
    set {_quota = newValue}
  }
  /// Returns true if `quota` has been explicitly set.
  var hasQuota: Bool {return self._quota != nil}
  /// Clears the value of `quota`. Subsequent reads from it will return its default value.
  mutating func clearQuota() {self._quota = nil}

  var needSignIn: Bool {
    get {return _needSignIn ?? false}
    set {_needSignIn = newValue}
  }
  /// Returns true if `needSignIn` has been explicitly set.
  var hasNeedSignIn: Bool {return self._needSignIn != nil}
  /// Clears the value of `needSignIn`. Subsequent reads from it will return its default value.
  mutating func clearNeedSignIn() {self._needSignIn = nil}

  var status: Campus_Activity_ActivityStatus {
    get {return _status ?? .unspecified}
    set {_status = newValue}
  }
  /// Returns true if `status` has been explicitly set.
  var hasStatus: Bool {return self._status != nil}
  /// Clears the value of `status`. Subsequent reads from it will return its default value.
  mutating func clearStatus() {self._status = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _title: String? = nil
  fileprivate var _content: String? = nil
  fileprivate var _coverURL: String? = nil
  fileprivate var _activityType: Campus_Activity_ActivityType? = nil
  fileprivate var _location: String? = nil
  fileprivate var _organizer: String? = nil
  fileprivate var _startTime: String? = nil
  fileprivate var _endTime: String? = nil
  fileprivate var _quota: Int32? = nil
  fileprivate var _needSignIn: Bool? = nil
  fileprivate var _status: Campus_Activity_ActivityStatus? = nil
}

/// 报名活动请求
struct Campus_Activity_EnrollActivityRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var userName: String = String()

  var studentID: String = String()

  var major: String = String()

  var phoneNumber: String {
    get {return _phoneNumber ?? String()}
    set {_phoneNumber = newValue}
  }
  /// Returns true if `phoneNumber` has been explicitly set.
  var hasPhoneNumber: Bool {return self._phoneNumber != nil}
  /// Clears the value of `phoneNumber`. Subsequent reads from it will return its default value.
  mutating func clearPhoneNumber() {self._phoneNumber = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _phoneNumber: String? = nil
}

/// 我的活动请求
struct Campus_Activity_GetMyActivitiesRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var includeEnrollments: Bool = false

  var includeCollections: Bool = false

  var page: Int32 = 0

  var pageSize: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// 通用响应包装
struct Campus_Activity_ApiResponse: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var code: Int32 = 0

  var message: String = String()

  /// 实际数据的序列化内容
  var data: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// 活动列表响应
struct Campus_Activity_GetActivitiesResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var list: [Campus_Activity_ActivityListItem] = []

  var pagination: Campus_Activity_Pagination {
    get {return _pagination ?? Campus_Activity_Pagination()}
    set {_pagination = newValue}
  }
  /// Returns true if `pagination` has been explicitly set.
  var hasPagination: Bool {return self._pagination != nil}
  /// Clears the value of `pagination`. Subsequent reads from it will return its default value.
  mutating func clearPagination() {self._pagination = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _pagination: Campus_Activity_Pagination? = nil
}

/// 活动详情响应
struct Campus_Activity_GetActivityDetailResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var detail: Campus_Activity_ActivityDetail {
    get {return _detail ?? Campus_Activity_ActivityDetail()}
    set {_detail = newValue}
  }
  /// Returns true if `detail` has been explicitly set.
  var hasDetail: Bool {return self._detail != nil}
  /// Clears the value of `detail`. Subsequent reads from it will return its default value.
  mutating func clearDetail() {self._detail = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _detail: Campus_Activity_ActivityDetail? = nil
}

/// 创建活动响应
struct Campus_Activity_CreateActivityResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var activities: [Campus_Activity_Activity] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// 报名列表响应
struct Campus_Activity_GetEnrollmentsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var totalEnrolled: Int32 = 0

  var enrollmentList: [Campus_Activity_EnrollmentRecord] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// 我的活动响应 - 报名数据
struct Campus_Activity_EnrolledData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var list: [Campus_Activity_MyEnrollmentItem] = []

  var pagination: Campus_Activity_Pagination {
    get {return _pagination ?? Campus_Activity_Pagination()}
    set {_pagination = newValue}
  }
  /// Returns true if `pagination` has been explicitly set.
  var hasPagination: Bool {return self._pagination != nil}
  /// Clears the value of `pagination`. Subsequent reads from it will return its default value.
  mutating func clearPagination() {self._pagination = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _pagination: Campus_Activity_Pagination? = nil
}

/// 我的活动响应 - 收藏数据
struct Campus_Activity_CollectedData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var list: [Campus_Activity_MyCollectionItem] = []

  var pagination: Campus_Activity_Pagination {
    get {return _pagination ?? Campus_Activity_Pagination()}
    set {_pagination = newValue}
  }
  /// Returns true if `pagination` has been explicitly set.
  var hasPagination: Bool {return self._pagination != nil}
  /// Clears the value of `pagination`. Subsequent reads from it will return its default value.
  mutating func clearPagination() {self._pagination = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _pagination: Campus_Activity_Pagination? = nil
}

/// 我的活动响应
struct Campus_Activity_GetMyActivitiesResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var enrolledData: Campus_Activity_EnrolledData {
    get {return _enrolledData ?? Campus_Activity_EnrolledData()}
    set {_enrolledData = newValue}
  }
  /// Returns true if `enrolledData` has been explicitly set.
  var hasEnrolledData: Bool {return self._enrolledData != nil}
  /// Clears the value of `enrolledData`. Subsequent reads from it will return its default value.
  mutating func clearEnrolledData() {self._enrolledData = nil}

  var collectedData: Campus_Activity_CollectedData {
    get {return _collectedData ?? Campus_Activity_CollectedData()}
    set {_collectedData = newValue}
  }
  /// Returns true if `collectedData` has been explicitly set.
  var hasCollectedData: Bool {return self._collectedData != nil}
  /// Clears the value of `collectedData`. Subsequent reads from it will return its default value.
  mutating func clearCollectedData() {self._collectedData = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _enrolledData: Campus_Activity_EnrolledData? = nil
  fileprivate var _collectedData: Campus_Activity_CollectedData? = nil
}

/// 简单成功响应（无数据）
struct Campus_Activity_EmptyResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "campus.activity"

extension Campus_Activity_ActivityStatus: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "ACTIVITY_STATUS_UNSPECIFIED"),
    1: .same(proto: "ONGOING"),
    2: .same(proto: "ENDED"),
    3: .same(proto: "CANCELLED"),
  ]
}

extension Campus_Activity_ActivityType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "ACTIVITY_TYPE_UNSPECIFIED"),
    1: .same(proto: "LECTURE"),
    2: .same(proto: "CLUB"),
    3: .same(proto: "COMPETITION"),
  ]
}

extension Campus_Activity_Pagination: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Pagination"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "total"),
    2: .same(proto: "page"),
    3: .standard(proto: "page_size"),
    4: .same(proto: "pages"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.total) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.page) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.pageSize) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.pages) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.total != 0 {
      try visitor.visitSingularInt64Field(value: self.total, fieldNumber: 1)
    }
    if self.page != 0 {
      try visitor.visitSingularInt32Field(value: self.page, fieldNumber: 2)
    }
    if self.pageSize != 0 {
      try visitor.visitSingularInt32Field(value: self.pageSize, fieldNumber: 3)
    }
    if self.pages != 0 {
      try visitor.visitSingularInt32Field(value: self.pages, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_Activity_Pagination, rhs: Campus_Activity_Pagination) -> Bool {
    if lhs.total != rhs.total {return false}
    if lhs.page != rhs.page {return false}
    if lhs.pageSize != rhs.pageSize {return false}
    if lhs.pages != rhs.pages {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Campus_Activity_ActivityListItem: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ActivityListItem"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "title"),
    3: .standard(proto: "cover_url"),
    4: .same(proto: "location"),
    5: .standard(proto: "start_time"),
    6: .same(proto: "quota"),
    7: .standard(proto: "current_enrollments"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.coverURL) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.location) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.startTime) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self.quota) }()
      case 7: try { try decoder.decodeSingularInt32Field(value: &self.currentEnrollments) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 2)
    }
    if !self.coverURL.isEmpty {
      try visitor.visitSingularStringField(value: self.coverURL, fieldNumber: 3)
    }
    if !self.location.isEmpty {
      try visitor.visitSingularStringField(value: self.location, fieldNumber: 4)
    }
    if !self.startTime.isEmpty {
      try visitor.visitSingularStringField(value: self.startTime, fieldNumber: 5)
    }
    if self.quota != 0 {
      try visitor.visitSingularInt32Field(value: self.quota, fieldNumber: 6)
    }
    if self.currentEnrollments != 0 {
      try visitor.visitSingularInt32Field(value: self.currentEnrollments, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_Activity_ActivityListItem, rhs: Campus_Activity_ActivityListItem) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.title != rhs.title {return false}
    if lhs.coverURL != rhs.coverURL {return false}
    if lhs.location != rhs.location {return false}
    if lhs.startTime != rhs.startTime {return false}
    if lhs.quota != rhs.quota {return false}
    if lhs.currentEnrollments != rhs.currentEnrollments {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Campus_Activity_Activity: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Activity"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .same(proto: "title"),
    3: .same(proto: "content"),
    4: .standard(proto: "cover_url"),
    5: .standard(proto: "activity_type"),
    6: .same(proto: "location"),
    7: .same(proto: "organizer"),
    8: .standard(proto: "start_time"),
    9: .standard(proto: "end_time"),
    10: .same(proto: "quota"),
    11: .standard(proto: "current_enrollments"),
    12: .standard(proto: "need_sign_in"),
    13: .same(proto: "status"),
    14: .standard(proto: "created_at"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.content) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.coverURL) }()
      case 5: try { try decoder.decodeSingularEnumField(value: &self.activityType) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.location) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.organizer) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.startTime) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.endTime) }()
      case 10: try { try decoder.decodeSingularInt32Field(value: &self.quota) }()
      case 11: try { try decoder.decodeSingularInt32Field(value: &self.currentEnrollments) }()
      case 12: try { try decoder.decodeSingularBoolField(value: &self.needSignIn) }()
      case 13: try { try decoder.decodeSingularEnumField(value: &self.status) }()
      case 14: try { try decoder.decodeSingularStringField(value: &self.createdAt) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 2)
    }
    if !self.content.isEmpty {
      try visitor.visitSingularStringField(value: self.content, fieldNumber: 3)
    }
    if !self.coverURL.isEmpty {
      try visitor.visitSingularStringField(value: self.coverURL, fieldNumber: 4)
    }
    if self.activityType != .unspecified {
      try visitor.visitSingularEnumField(value: self.activityType, fieldNumber: 5)
    }
    if !self.location.isEmpty {
      try visitor.visitSingularStringField(value: self.location, fieldNumber: 6)
    }
    if !self.organizer.isEmpty {
      try visitor.visitSingularStringField(value: self.organizer, fieldNumber: 7)
    }
    if !self.startTime.isEmpty {
      try visitor.visitSingularStringField(value: self.startTime, fieldNumber: 8)
    }
    if !self.endTime.isEmpty {
      try visitor.visitSingularStringField(value: self.endTime, fieldNumber: 9)
    }
    if self.quota != 0 {
      try visitor.visitSingularInt32Field(value: self.quota, fieldNumber: 10)
    }
    if self.currentEnrollments != 0 {
      try visitor.visitSingularInt32Field(value: self.currentEnrollments, fieldNumber: 11)
    }
    if self.needSignIn != false {
      try visitor.visitSingularBoolField(value: self.needSignIn, fieldNumber: 12)
    }
    if self.status != .unspecified {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 13)
    }
    if !self.createdAt.isEmpty {
      try visitor.visitSingularStringField(value: self.createdAt, fieldNumber: 14)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_Activity_Activity, rhs: Campus_Activity_Activity) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.title != rhs.title {return false}
    if lhs.content != rhs.content {return false}
    if lhs.coverURL != rhs.coverURL {return false}
    if lhs.activityType != rhs.activityType {return false}
    if lhs.location != rhs.location {return false}
    if lhs.organizer != rhs.organizer {return false}
    if lhs.startTime != rhs.startTime {return false}
    if lhs.endTime != rhs.endTime {return false}
    if lhs.quota != rhs.quota {return false}
    if lhs.currentEnrollments != rhs.currentEnrollments {return false}
    if lhs.needSignIn != rhs.needSignIn {return false}
    if lhs.status != rhs.status {return false}
    if lhs.createdAt != rhs.createdAt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Campus_Activity_ActivityDetail: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ActivityDetail"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "activity"),
    2: .standard(proto: "is_enrolled"),
    3: .standard(proto: "is_collected"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._activity) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.isEnrolled) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.isCollected) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._activity {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.isEnrolled != false {
      try visitor.visitSingularBoolField(value: self.isEnrolled, fieldNumber: 2)
    }
    if self.isCollected != false {
      try visitor.visitSingularBoolField(value: self.isCollected, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_Activity_ActivityDetail, rhs: Campus_Activity_ActivityDetail) -> Bool {
    if lhs._activity != rhs._activity {return false}
    if lhs.isEnrolled != rhs.isEnrolled {return false}
    if lhs.isCollected != rhs.isCollected {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Campus_Activity_EnrollmentRecord: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".EnrollmentRecord"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "user_id"),
    2: .standard(proto: "user_name"),
    3: .standard(proto: "student_id"),
    4: .same(proto: "major"),
    5: .standard(proto: "phone_number"),
    6: .standard(proto: "activity_id"),
    7: .standard(proto: "enroll_time"),
    8: .standard(proto: "attendance_status"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.userID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.userName) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.studentID) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.major) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.phoneNumber) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.activityID) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.enrollTime) }()
      case 8: try { try decoder.decodeSingularInt32Field(value: &self.attendanceStatus) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.userID.isEmpty {
      try visitor.visitSingularStringField(value: self.userID, fieldNumber: 1)
    }
    if !self.userName.isEmpty {
      try visitor.visitSingularStringField(value: self.userName, fieldNumber: 2)
    }
    if !self.studentID.isEmpty {
      try visitor.visitSingularStringField(value: self.studentID, fieldNumber: 3)
    }
    if !self.major.isEmpty {
      try visitor.visitSingularStringField(value: self.major, fieldNumber: 4)
    }
    if !self.phoneNumber.isEmpty {
      try visitor.visitSingularStringField(value: self.phoneNumber, fieldNumber: 5)
    }
    if !self.activityID.isEmpty {
      try visitor.visitSingularStringField(value: self.activityID, fieldNumber: 6)
    }
    if !self.enrollTime.isEmpty {
      try visitor.visitSingularStringField(value: self.enrollTime, fieldNumber: 7)
    }
    if self.attendanceStatus != 0 {
      try visitor.visitSingularInt32Field(value: self.attendanceStatus, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_Activity_EnrollmentRecord, rhs: Campus_Activity_EnrollmentRecord) -> Bool {
    if lhs.userID != rhs.userID {return false}
    if lhs.userName != rhs.userName {return false}
    if lhs.studentID != rhs.studentID {return false}
    if lhs.major != rhs.major {return false}
    if lhs.phoneNumber != rhs.phoneNumber {return false}
    if lhs.activityID != rhs.activityID {return false}
    if lhs.enrollTime != rhs.enrollTime {return false}
    if lhs.attendanceStatus != rhs.attendanceStatus {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Campus_Activity_MyEnrollmentItem: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MyEnrollmentItem"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "activity_id"),
    2: .same(proto: "title"),
    3: .standard(proto: "cover_url"),
    4: .standard(proto: "start_time"),
    5: .standard(proto: "end_time"),
    6: .standard(proto: "my_status"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.activityID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.coverURL) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.startTime) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.endTime) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self.myStatus) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.activityID.isEmpty {
      try visitor.visitSingularStringField(value: self.activityID, fieldNumber: 1)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 2)
    }
    if !self.coverURL.isEmpty {
      try visitor.visitSingularStringField(value: self.coverURL, fieldNumber: 3)
    }
    if !self.startTime.isEmpty {
      try visitor.visitSingularStringField(value: self.startTime, fieldNumber: 4)
    }
    if !self.endTime.isEmpty {
      try visitor.visitSingularStringField(value: self.endTime, fieldNumber: 5)
    }
    if self.myStatus != 0 {
      try visitor.visitSingularInt32Field(value: self.myStatus, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_Activity_MyEnrollmentItem, rhs: Campus_Activity_MyEnrollmentItem) -> Bool {
    if lhs.activityID != rhs.activityID {return false}
    if lhs.title != rhs.title {return false}
    if lhs.coverURL != rhs.coverURL {return false}
    if lhs.startTime != rhs.startTime {return false}
    if lhs.endTime != rhs.endTime {return false}
    if lhs.myStatus != rhs.myStatus {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Campus_Activity_MyCollectionItem: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MyCollectionItem"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "activity_id"),
    2: .same(proto: "title"),
    3: .standard(proto: "cover_url"),
    4: .standard(proto: "start_time"),
    5: .standard(proto: "end_time"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.activityID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.coverURL) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.startTime) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.endTime) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.activityID.isEmpty {
      try visitor.visitSingularStringField(value: self.activityID, fieldNumber: 1)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 2)
    }
    if !self.coverURL.isEmpty {
      try visitor.visitSingularStringField(value: self.coverURL, fieldNumber: 3)
    }
    if !self.startTime.isEmpty {
      try visitor.visitSingularStringField(value: self.startTime, fieldNumber: 4)
    }
    if !self.endTime.isEmpty {
      try visitor.visitSingularStringField(value: self.endTime, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_Activity_MyCollectionItem, rhs: Campus_Activity_MyCollectionItem) -> Bool {
    if lhs.activityID != rhs.activityID {return false}
    if lhs.title != rhs.title {return false}
    if lhs.coverURL != rhs.coverURL {return false}
    if lhs.startTime != rhs.startTime {return false}
    if lhs.endTime != rhs.endTime {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Campus_Activity_GetActivitiesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetActivitiesRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "keyword"),
    2: .standard(proto: "activity_type"),
    3: .same(proto: "page"),
    4: .standard(proto: "page_size"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._keyword) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self._activityType) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.page) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.pageSize) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._keyword {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._activityType {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 2)
    } }()
    if self.page != 0 {
      try visitor.visitSingularInt32Field(value: self.page, fieldNumber: 3)
    }
    if self.pageSize != 0 {
      try visitor.visitSingularInt32Field(value: self.pageSize, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_Activity_GetActivitiesRequest, rhs: Campus_Activity_GetActivitiesRequest) -> Bool {
    if lhs._keyword != rhs._keyword {return false}
    if lhs._activityType != rhs._activityType {return false}
    if lhs.page != rhs.page {return false}
    if lhs.pageSize != rhs.pageSize {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Campus_Activity_CreateActivityRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CreateActivityRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "title"),
    2: .same(proto: "content"),
    3: .same(proto: "location"),
    4: .same(proto: "organizer"),
    5: .standard(proto: "start_time"),
    6: .standard(proto: "end_time"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.content) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.location) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.organizer) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.startTime) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.endTime) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 1)
    }
    if !self.content.isEmpty {
      try visitor.visitSingularStringField(value: self.content, fieldNumber: 2)
    }
    if !self.location.isEmpty {
      try visitor.visitSingularStringField(value: self.location, fieldNumber: 3)
    }
    if !self.organizer.isEmpty {
      try visitor.visitSingularStringField(value: self.organizer, fieldNumber: 4)
    }
    if !self.startTime.isEmpty {
      try visitor.visitSingularStringField(value: self.startTime, fieldNumber: 5)
    }
    if !self.endTime.isEmpty {
      try visitor.visitSingularStringField(value: self.endTime, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_Activity_CreateActivityRequest, rhs: Campus_Activity_CreateActivityRequest) -> Bool {
    if lhs.title != rhs.title {return false}
    if lhs.content != rhs.content {return false}
    if lhs.location != rhs.location {return false}
    if lhs.organizer != rhs.organizer {return false}
    if lhs.startTime != rhs.startTime {return false}
    if lhs.endTime != rhs.endTime {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Campus_Activity_UpdateActivityRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UpdateActivityRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "title"),
    2: .same(proto: "content"),
    3: .standard(proto: "cover_url"),
    4: .standard(proto: "activity_type"),
    5: .same(proto: "location"),
    6: .same(proto: "organizer"),
    7: .standard(proto: "start_time"),
    8: .standard(proto: "end_time"),
    9: .same(proto: "quota"),
    10: .standard(proto: "need_sign_in"),
    11: .same(proto: "status"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._title) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._content) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._coverURL) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self._activityType) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._location) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._organizer) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._startTime) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self._endTime) }()
      case 9: try { try decoder.decodeSingularInt32Field(value: &self._quota) }()
      case 10: try { try decoder.decodeSingularBoolField(value: &self._needSignIn) }()
      case 11: try { try decoder.decodeSingularEnumField(value: &self._status) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._title {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._content {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._coverURL {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._activityType {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._location {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._organizer {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._startTime {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._endTime {
      try visitor.visitSingularStringField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._quota {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 9)
    } }()
    try { if let v = self._needSignIn {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 10)
    } }()
    try { if let v = self._status {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 11)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_Activity_UpdateActivityRequest, rhs: Campus_Activity_UpdateActivityRequest) -> Bool {
    if lhs._title != rhs._title {return false}
    if lhs._content != rhs._content {return false}
    if lhs._coverURL != rhs._coverURL {return false}
    if lhs._activityType != rhs._activityType {return false}
    if lhs._location != rhs._location {return false}
    if lhs._organizer != rhs._organizer {return false}
    if lhs._startTime != rhs._startTime {return false}
    if lhs._endTime != rhs._endTime {return false}
    if lhs._quota != rhs._quota {return false}
    if lhs._needSignIn != rhs._needSignIn {return false}
    if lhs._status != rhs._status {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Campus_Activity_EnrollActivityRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".EnrollActivityRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "user_name"),
    2: .standard(proto: "student_id"),
    3: .same(proto: "major"),
    4: .standard(proto: "phone_number"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.userName) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.studentID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.major) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._phoneNumber) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.userName.isEmpty {
      try visitor.visitSingularStringField(value: self.userName, fieldNumber: 1)
    }
    if !self.studentID.isEmpty {
      try visitor.visitSingularStringField(value: self.studentID, fieldNumber: 2)
    }
    if !self.major.isEmpty {
      try visitor.visitSingularStringField(value: self.major, fieldNumber: 3)
    }
    try { if let v = self._phoneNumber {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_Activity_EnrollActivityRequest, rhs: Campus_Activity_EnrollActivityRequest) -> Bool {
    if lhs.userName != rhs.userName {return false}
    if lhs.studentID != rhs.studentID {return false}
    if lhs.major != rhs.major {return false}
    if lhs._phoneNumber != rhs._phoneNumber {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Campus_Activity_GetMyActivitiesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetMyActivitiesRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "include_enrollments"),
    2: .standard(proto: "include_collections"),
    3: .same(proto: "page"),
    4: .standard(proto: "page_size"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.includeEnrollments) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.includeCollections) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.page) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.pageSize) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.includeEnrollments != false {
      try visitor.visitSingularBoolField(value: self.includeEnrollments, fieldNumber: 1)
    }
    if self.includeCollections != false {
      try visitor.visitSingularBoolField(value: self.includeCollections, fieldNumber: 2)
    }
    if self.page != 0 {
      try visitor.visitSingularInt32Field(value: self.page, fieldNumber: 3)
    }
    if self.pageSize != 0 {
      try visitor.visitSingularInt32Field(value: self.pageSize, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_Activity_GetMyActivitiesRequest, rhs: Campus_Activity_GetMyActivitiesRequest) -> Bool {
    if lhs.includeEnrollments != rhs.includeEnrollments {return false}
    if lhs.includeCollections != rhs.includeCollections {return false}
    if lhs.page != rhs.page {return false}
    if lhs.pageSize != rhs.pageSize {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Campus_Activity_ApiResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ApiResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "code"),
    2: .same(proto: "message"),
    3: .same(proto: "data"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.code) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.data) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.code != 0 {
      try visitor.visitSingularInt32Field(value: self.code, fieldNumber: 1)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 2)
    }
    if !self.data.isEmpty {
      try visitor.visitSingularBytesField(value: self.data, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_Activity_ApiResponse, rhs: Campus_Activity_ApiResponse) -> Bool {
    if lhs.code != rhs.code {return false}
    if lhs.message != rhs.message {return false}
    if lhs.data != rhs.data {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Campus_Activity_GetActivitiesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetActivitiesResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "list"),
    2: .same(proto: "pagination"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.list) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._pagination) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.list.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.list, fieldNumber: 1)
    }
    try { if let v = self._pagination {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_Activity_GetActivitiesResponse, rhs: Campus_Activity_GetActivitiesResponse) -> Bool {
    if lhs.list != rhs.list {return false}
    if lhs._pagination != rhs._pagination {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Campus_Activity_GetActivityDetailResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetActivityDetailResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "detail"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._detail) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._detail {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_Activity_GetActivityDetailResponse, rhs: Campus_Activity_GetActivityDetailResponse) -> Bool {
    if lhs._detail != rhs._detail {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Campus_Activity_CreateActivityResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CreateActivityResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "activities"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.activities) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.activities.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.activities, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_Activity_CreateActivityResponse, rhs: Campus_Activity_CreateActivityResponse) -> Bool {
    if lhs.activities != rhs.activities {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Campus_Activity_GetEnrollmentsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetEnrollmentsResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "total_enrolled"),
    2: .standard(proto: "enrollment_list"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.totalEnrolled) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.enrollmentList) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.totalEnrolled != 0 {
      try visitor.visitSingularInt32Field(value: self.totalEnrolled, fieldNumber: 1)
    }
    if !self.enrollmentList.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.enrollmentList, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_Activity_GetEnrollmentsResponse, rhs: Campus_Activity_GetEnrollmentsResponse) -> Bool {
    if lhs.totalEnrolled != rhs.totalEnrolled {return false}
    if lhs.enrollmentList != rhs.enrollmentList {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Campus_Activity_EnrolledData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".EnrolledData"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "list"),
    2: .same(proto: "pagination"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.list) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._pagination) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.list.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.list, fieldNumber: 1)
    }
    try { if let v = self._pagination {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_Activity_EnrolledData, rhs: Campus_Activity_EnrolledData) -> Bool {
    if lhs.list != rhs.list {return false}
    if lhs._pagination != rhs._pagination {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Campus_Activity_CollectedData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CollectedData"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "list"),
    2: .same(proto: "pagination"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.list) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._pagination) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.list.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.list, fieldNumber: 1)
    }
    try { if let v = self._pagination {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_Activity_CollectedData, rhs: Campus_Activity_CollectedData) -> Bool {
    if lhs.list != rhs.list {return false}
    if lhs._pagination != rhs._pagination {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Campus_Activity_GetMyActivitiesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetMyActivitiesResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "enrolled_data"),
    2: .standard(proto: "collected_data"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._enrolledData) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._collectedData) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._enrolledData {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._collectedData {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_Activity_GetMyActivitiesResponse, rhs: Campus_Activity_GetMyActivitiesResponse) -> Bool {
    if lhs._enrolledData != rhs._enrolledData {return false}
    if lhs._collectedData != rhs._collectedData {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Campus_Activity_EmptyResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".EmptyResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_Activity_EmptyResponse, rhs: Campus_Activity_EmptyResponse) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
