// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Protocol/user.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// 用户信息
struct Campus_User_UserInfo: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: String {
    get {return _storage._id}
    set {_uniqueStorage()._id = newValue}
  }

  var studentID: String {
    get {return _storage._studentID}
    set {_uniqueStorage()._studentID = newValue}
  }

  var name: String {
    get {return _storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  var avatarURL: String {
    get {return _storage._avatarURL}
    set {_uniqueStorage()._avatarURL = newValue}
  }

  var role: String {
    get {return _storage._role}
    set {_uniqueStorage()._role = newValue}
  }

  var college: String {
    get {return _storage._college}
    set {_uniqueStorage()._college = newValue}
  }

  var major: String {
    get {return _storage._major}
    set {_uniqueStorage()._major = newValue}
  }

  var grade: String {
    get {return _storage._grade}
    set {_uniqueStorage()._grade = newValue}
  }

  var className: String {
    get {return _storage._className}
    set {_uniqueStorage()._className = newValue}
  }

  var bio: String {
    get {return _storage._bio}
    set {_uniqueStorage()._bio = newValue}
  }

  var phone: String {
    get {return _storage._phone}
    set {_uniqueStorage()._phone = newValue}
  }

  var email: String {
    get {return _storage._email}
    set {_uniqueStorage()._email = newValue}
  }

  var wechatID: String {
    get {return _storage._wechatID}
    set {_uniqueStorage()._wechatID = newValue}
  }

  var weeklyCourseCount: Int32 {
    get {return _storage._weeklyCourseCount}
    set {_uniqueStorage()._weeklyCourseCount = newValue}
  }

  var forumActivityScore: Int32 {
    get {return _storage._forumActivityScore}
    set {_uniqueStorage()._forumActivityScore = newValue}
  }

  var collectionCount: Int32 {
    get {return _storage._collectionCount}
    set {_uniqueStorage()._collectionCount = newValue}
  }

  var settingPrivacyCourse: String {
    get {return _storage._settingPrivacyCourse}
    set {_uniqueStorage()._settingPrivacyCourse = newValue}
  }

  var settingNotificationSwitch: Bool {
    get {return _storage._settingNotificationSwitch}
    set {_uniqueStorage()._settingNotificationSwitch = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// 登录请求
struct Campus_User_LoginRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var studentID: String = String()

  var password: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// 注册请求
struct Campus_User_RegisterRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var studentID: String = String()

  var password: String = String()

  var name: String = String()

  var college: String = String()

  var major: String = String()

  var phone: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// 更新资料请求
struct Campus_User_UpdateProfileRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String {
    get {return _name ?? String()}
    set {_name = newValue}
  }
  /// Returns true if `name` has been explicitly set.
  var hasName: Bool {return self._name != nil}
  /// Clears the value of `name`. Subsequent reads from it will return its default value.
  mutating func clearName() {self._name = nil}

  var avatarURL: String {
    get {return _avatarURL ?? String()}
    set {_avatarURL = newValue}
  }
  /// Returns true if `avatarURL` has been explicitly set.
  var hasAvatarURL: Bool {return self._avatarURL != nil}
  /// Clears the value of `avatarURL`. Subsequent reads from it will return its default value.
  mutating func clearAvatarURL() {self._avatarURL = nil}

  var bio: String {
    get {return _bio ?? String()}
    set {_bio = newValue}
  }
  /// Returns true if `bio` has been explicitly set.
  var hasBio: Bool {return self._bio != nil}
  /// Clears the value of `bio`. Subsequent reads from it will return its default value.
  mutating func clearBio() {self._bio = nil}

  var phone: String {
    get {return _phone ?? String()}
    set {_phone = newValue}
  }
  /// Returns true if `phone` has been explicitly set.
  var hasPhone: Bool {return self._phone != nil}
  /// Clears the value of `phone`. Subsequent reads from it will return its default value.
  mutating func clearPhone() {self._phone = nil}

  var email: String {
    get {return _email ?? String()}
    set {_email = newValue}
  }
  /// Returns true if `email` has been explicitly set.
  var hasEmail: Bool {return self._email != nil}
  /// Clears the value of `email`. Subsequent reads from it will return its default value.
  mutating func clearEmail() {self._email = nil}

  var wechatID: String {
    get {return _wechatID ?? String()}
    set {_wechatID = newValue}
  }
  /// Returns true if `wechatID` has been explicitly set.
  var hasWechatID: Bool {return self._wechatID != nil}
  /// Clears the value of `wechatID`. Subsequent reads from it will return its default value.
  mutating func clearWechatID() {self._wechatID = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _name: String? = nil
  fileprivate var _avatarURL: String? = nil
  fileprivate var _bio: String? = nil
  fileprivate var _phone: String? = nil
  fileprivate var _email: String? = nil
  fileprivate var _wechatID: String? = nil
}

/// 修改密码请求
struct Campus_User_ChangePasswordRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var oldPassword: String = String()

  var newPassword: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// 登录响应
struct Campus_User_LoginResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var token: String = String()

  var user: Campus_User_UserInfo {
    get {return _user ?? Campus_User_UserInfo()}
    set {_user = newValue}
  }
  /// Returns true if `user` has been explicitly set.
  var hasUser: Bool {return self._user != nil}
  /// Clears the value of `user`. Subsequent reads from it will return its default value.
  mutating func clearUser() {self._user = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _user: Campus_User_UserInfo? = nil
}

/// 注册响应
struct Campus_User_RegisterResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var userID: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// 获取用户信息响应
struct Campus_User_GetUserInfoResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var user: Campus_User_UserInfo {
    get {return _user ?? Campus_User_UserInfo()}
    set {_user = newValue}
  }
  /// Returns true if `user` has been explicitly set.
  var hasUser: Bool {return self._user != nil}
  /// Clears the value of `user`. Subsequent reads from it will return its default value.
  mutating func clearUser() {self._user = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _user: Campus_User_UserInfo? = nil
}

/// 简单成功响应（无数据）
struct Campus_User_EmptyResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "campus.user"

extension Campus_User_UserInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UserInfo"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "id"),
    2: .standard(proto: "student_id"),
    3: .same(proto: "name"),
    4: .standard(proto: "avatar_url"),
    5: .same(proto: "role"),
    6: .same(proto: "college"),
    7: .same(proto: "major"),
    8: .same(proto: "grade"),
    9: .standard(proto: "class_name"),
    10: .same(proto: "bio"),
    11: .same(proto: "phone"),
    12: .same(proto: "email"),
    13: .standard(proto: "wechat_id"),
    14: .standard(proto: "weekly_course_count"),
    15: .standard(proto: "forum_activity_score"),
    16: .standard(proto: "collection_count"),
    17: .standard(proto: "setting_privacy_course"),
    18: .standard(proto: "setting_notification_switch"),
  ]

  fileprivate class _StorageClass {
    var _id: String = String()
    var _studentID: String = String()
    var _name: String = String()
    var _avatarURL: String = String()
    var _role: String = String()
    var _college: String = String()
    var _major: String = String()
    var _grade: String = String()
    var _className: String = String()
    var _bio: String = String()
    var _phone: String = String()
    var _email: String = String()
    var _wechatID: String = String()
    var _weeklyCourseCount: Int32 = 0
    var _forumActivityScore: Int32 = 0
    var _collectionCount: Int32 = 0
    var _settingPrivacyCourse: String = String()
    var _settingNotificationSwitch: Bool = false

    #if swift(>=5.10)
      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()
    #else
      static let defaultInstance = _StorageClass()
    #endif

    private init() {}

    init(copying source: _StorageClass) {
      _id = source._id
      _studentID = source._studentID
      _name = source._name
      _avatarURL = source._avatarURL
      _role = source._role
      _college = source._college
      _major = source._major
      _grade = source._grade
      _className = source._className
      _bio = source._bio
      _phone = source._phone
      _email = source._email
      _wechatID = source._wechatID
      _weeklyCourseCount = source._weeklyCourseCount
      _forumActivityScore = source._forumActivityScore
      _collectionCount = source._collectionCount
      _settingPrivacyCourse = source._settingPrivacyCourse
      _settingNotificationSwitch = source._settingNotificationSwitch
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._id) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._studentID) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._name) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._avatarURL) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._role) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._college) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._major) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._grade) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._className) }()
        case 10: try { try decoder.decodeSingularStringField(value: &_storage._bio) }()
        case 11: try { try decoder.decodeSingularStringField(value: &_storage._phone) }()
        case 12: try { try decoder.decodeSingularStringField(value: &_storage._email) }()
        case 13: try { try decoder.decodeSingularStringField(value: &_storage._wechatID) }()
        case 14: try { try decoder.decodeSingularInt32Field(value: &_storage._weeklyCourseCount) }()
        case 15: try { try decoder.decodeSingularInt32Field(value: &_storage._forumActivityScore) }()
        case 16: try { try decoder.decodeSingularInt32Field(value: &_storage._collectionCount) }()
        case 17: try { try decoder.decodeSingularStringField(value: &_storage._settingPrivacyCourse) }()
        case 18: try { try decoder.decodeSingularBoolField(value: &_storage._settingNotificationSwitch) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._id.isEmpty {
        try visitor.visitSingularStringField(value: _storage._id, fieldNumber: 1)
      }
      if !_storage._studentID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._studentID, fieldNumber: 2)
      }
      if !_storage._name.isEmpty {
        try visitor.visitSingularStringField(value: _storage._name, fieldNumber: 3)
      }
      if !_storage._avatarURL.isEmpty {
        try visitor.visitSingularStringField(value: _storage._avatarURL, fieldNumber: 4)
      }
      if !_storage._role.isEmpty {
        try visitor.visitSingularStringField(value: _storage._role, fieldNumber: 5)
      }
      if !_storage._college.isEmpty {
        try visitor.visitSingularStringField(value: _storage._college, fieldNumber: 6)
      }
      if !_storage._major.isEmpty {
        try visitor.visitSingularStringField(value: _storage._major, fieldNumber: 7)
      }
      if !_storage._grade.isEmpty {
        try visitor.visitSingularStringField(value: _storage._grade, fieldNumber: 8)
      }
      if !_storage._className.isEmpty {
        try visitor.visitSingularStringField(value: _storage._className, fieldNumber: 9)
      }
      if !_storage._bio.isEmpty {
        try visitor.visitSingularStringField(value: _storage._bio, fieldNumber: 10)
      }
      if !_storage._phone.isEmpty {
        try visitor.visitSingularStringField(value: _storage._phone, fieldNumber: 11)
      }
      if !_storage._email.isEmpty {
        try visitor.visitSingularStringField(value: _storage._email, fieldNumber: 12)
      }
      if !_storage._wechatID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._wechatID, fieldNumber: 13)
      }
      if _storage._weeklyCourseCount != 0 {
        try visitor.visitSingularInt32Field(value: _storage._weeklyCourseCount, fieldNumber: 14)
      }
      if _storage._forumActivityScore != 0 {
        try visitor.visitSingularInt32Field(value: _storage._forumActivityScore, fieldNumber: 15)
      }
      if _storage._collectionCount != 0 {
        try visitor.visitSingularInt32Field(value: _storage._collectionCount, fieldNumber: 16)
      }
      if !_storage._settingPrivacyCourse.isEmpty {
        try visitor.visitSingularStringField(value: _storage._settingPrivacyCourse, fieldNumber: 17)
      }
      if _storage._settingNotificationSwitch != false {
        try visitor.visitSingularBoolField(value: _storage._settingNotificationSwitch, fieldNumber: 18)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_User_UserInfo, rhs: Campus_User_UserInfo) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._id != rhs_storage._id {return false}
        if _storage._studentID != rhs_storage._studentID {return false}
        if _storage._name != rhs_storage._name {return false}
        if _storage._avatarURL != rhs_storage._avatarURL {return false}
        if _storage._role != rhs_storage._role {return false}
        if _storage._college != rhs_storage._college {return false}
        if _storage._major != rhs_storage._major {return false}
        if _storage._grade != rhs_storage._grade {return false}
        if _storage._className != rhs_storage._className {return false}
        if _storage._bio != rhs_storage._bio {return false}
        if _storage._phone != rhs_storage._phone {return false}
        if _storage._email != rhs_storage._email {return false}
        if _storage._wechatID != rhs_storage._wechatID {return false}
        if _storage._weeklyCourseCount != rhs_storage._weeklyCourseCount {return false}
        if _storage._forumActivityScore != rhs_storage._forumActivityScore {return false}
        if _storage._collectionCount != rhs_storage._collectionCount {return false}
        if _storage._settingPrivacyCourse != rhs_storage._settingPrivacyCourse {return false}
        if _storage._settingNotificationSwitch != rhs_storage._settingNotificationSwitch {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Campus_User_LoginRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".LoginRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "student_id"),
    2: .same(proto: "password"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.studentID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.password) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.studentID.isEmpty {
      try visitor.visitSingularStringField(value: self.studentID, fieldNumber: 1)
    }
    if !self.password.isEmpty {
      try visitor.visitSingularStringField(value: self.password, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_User_LoginRequest, rhs: Campus_User_LoginRequest) -> Bool {
    if lhs.studentID != rhs.studentID {return false}
    if lhs.password != rhs.password {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Campus_User_RegisterRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RegisterRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "student_id"),
    2: .same(proto: "password"),
    3: .same(proto: "name"),
    4: .same(proto: "college"),
    5: .same(proto: "major"),
    6: .same(proto: "phone"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.studentID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.password) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.college) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.major) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.phone) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.studentID.isEmpty {
      try visitor.visitSingularStringField(value: self.studentID, fieldNumber: 1)
    }
    if !self.password.isEmpty {
      try visitor.visitSingularStringField(value: self.password, fieldNumber: 2)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 3)
    }
    if !self.college.isEmpty {
      try visitor.visitSingularStringField(value: self.college, fieldNumber: 4)
    }
    if !self.major.isEmpty {
      try visitor.visitSingularStringField(value: self.major, fieldNumber: 5)
    }
    if !self.phone.isEmpty {
      try visitor.visitSingularStringField(value: self.phone, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_User_RegisterRequest, rhs: Campus_User_RegisterRequest) -> Bool {
    if lhs.studentID != rhs.studentID {return false}
    if lhs.password != rhs.password {return false}
    if lhs.name != rhs.name {return false}
    if lhs.college != rhs.college {return false}
    if lhs.major != rhs.major {return false}
    if lhs.phone != rhs.phone {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Campus_User_UpdateProfileRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".UpdateProfileRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "name"),
    2: .standard(proto: "avatar_url"),
    3: .same(proto: "bio"),
    4: .same(proto: "phone"),
    5: .same(proto: "email"),
    6: .standard(proto: "wechat_id"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._avatarURL) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._bio) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._phone) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._email) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._wechatID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._name {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._avatarURL {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._bio {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._phone {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._email {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._wechatID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_User_UpdateProfileRequest, rhs: Campus_User_UpdateProfileRequest) -> Bool {
    if lhs._name != rhs._name {return false}
    if lhs._avatarURL != rhs._avatarURL {return false}
    if lhs._bio != rhs._bio {return false}
    if lhs._phone != rhs._phone {return false}
    if lhs._email != rhs._email {return false}
    if lhs._wechatID != rhs._wechatID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Campus_User_ChangePasswordRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ChangePasswordRequest"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "old_password"),
    2: .standard(proto: "new_password"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.oldPassword) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.newPassword) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.oldPassword.isEmpty {
      try visitor.visitSingularStringField(value: self.oldPassword, fieldNumber: 1)
    }
    if !self.newPassword.isEmpty {
      try visitor.visitSingularStringField(value: self.newPassword, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_User_ChangePasswordRequest, rhs: Campus_User_ChangePasswordRequest) -> Bool {
    if lhs.oldPassword != rhs.oldPassword {return false}
    if lhs.newPassword != rhs.newPassword {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Campus_User_LoginResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".LoginResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "token"),
    2: .same(proto: "user"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.token) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._user) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.token.isEmpty {
      try visitor.visitSingularStringField(value: self.token, fieldNumber: 1)
    }
    try { if let v = self._user {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_User_LoginResponse, rhs: Campus_User_LoginResponse) -> Bool {
    if lhs.token != rhs.token {return false}
    if lhs._user != rhs._user {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Campus_User_RegisterResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RegisterResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "user_id"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.userID) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.userID.isEmpty {
      try visitor.visitSingularStringField(value: self.userID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_User_RegisterResponse, rhs: Campus_User_RegisterResponse) -> Bool {
    if lhs.userID != rhs.userID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Campus_User_GetUserInfoResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetUserInfoResponse"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "user"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._user) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._user {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_User_GetUserInfoResponse, rhs: Campus_User_GetUserInfoResponse) -> Bool {
    if lhs._user != rhs._user {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Campus_User_EmptyResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".EmptyResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Campus_User_EmptyResponse, rhs: Campus_User_EmptyResponse) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
