// This file is @generated by prost-build.
/// 分页信息
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Pagination {
    #[prost(int64, tag = "1")]
    pub total: i64,
    #[prost(int32, tag = "2")]
    pub page: i32,
    #[prost(int32, tag = "3")]
    pub page_size: i32,
    #[prost(int32, tag = "4")]
    pub pages: i32,
}
/// 用户简要信息
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserLite {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub student_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub avatar_url: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub college: ::prost::alloc::string::String,
}
/// 媒体项
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MediaItem {
    /// image, video
    #[prost(string, tag = "1")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub url: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub thumbnail_url: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub meta: ::core::option::Option<MediaMeta>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MediaMeta {
    #[prost(string, tag = "1")]
    pub size: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub width: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub height: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub filename: ::prost::alloc::string::String,
}
/// 统计信息
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Stats {
    #[prost(int32, tag = "1")]
    pub view_count: i32,
    #[prost(int32, tag = "2")]
    pub like_count: i32,
    #[prost(int32, tag = "3")]
    pub comment_count: i32,
}
/// 用户交互信息
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserInteraction {
    #[prost(bool, tag = "1")]
    pub is_liked: bool,
    #[prost(bool, tag = "2")]
    pub is_collected: bool,
}
/// 评论统计
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommentStats {
    #[prost(int32, tag = "1")]
    pub like_count: i32,
}
/// 评论用户交互
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommentUserInteraction {
    #[prost(bool, tag = "1")]
    pub is_liked: bool,
}
/// 板块
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Board {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub icon: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub description: ::prost::alloc::string::String,
    /// static or dynamic
    #[prost(string, tag = "5")]
    pub board_type: ::prost::alloc::string::String,
}
/// 帖子列表项
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PostListItem {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub author: ::core::option::Option<UserLite>,
    #[prost(string, tag = "4")]
    pub board_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub board_name: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "7")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "8")]
    pub cover_image_url: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub summary: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "10")]
    pub stats: ::core::option::Option<Stats>,
    #[prost(message, optional, tag = "11")]
    pub user_interaction: ::core::option::Option<UserInteraction>,
}
/// 帖子详情
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PostDetail {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub content: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub board_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub board_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "6")]
    pub author: ::core::option::Option<UserLite>,
    #[prost(string, repeated, tag = "7")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "8")]
    pub media: ::prost::alloc::vec::Vec<MediaItem>,
    #[prost(message, optional, tag = "9")]
    pub stats: ::core::option::Option<Stats>,
    #[prost(message, optional, tag = "10")]
    pub user_interaction: ::core::option::Option<UserInteraction>,
    #[prost(string, tag = "11")]
    pub status: ::prost::alloc::string::String,
    #[prost(int32, tag = "12")]
    pub report_count: i32,
    #[prost(string, tag = "13")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag = "14")]
    pub last_replied_at: ::prost::alloc::string::String,
}
/// 评论详情
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommentDetail {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub post_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub author: ::core::option::Option<UserLite>,
    #[prost(string, tag = "4")]
    pub content: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub parent_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "6")]
    pub reply_to: ::core::option::Option<UserLite>,
    #[prost(message, optional, tag = "7")]
    pub stats: ::core::option::Option<CommentStats>,
    #[prost(message, optional, tag = "8")]
    pub user_interaction: ::core::option::Option<CommentUserInteraction>,
    #[prost(string, tag = "9")]
    pub created_at: ::prost::alloc::string::String,
}
/// 获取板块列表请求（无参数）
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBoardsRequest {}
/// 获取帖子列表请求
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPostsRequest {
    #[prost(int32, tag = "1")]
    pub page: i32,
    #[prost(int32, tag = "2")]
    pub page_size: i32,
    #[prost(string, optional, tag = "3")]
    pub board_id: ::core::option::Option<::prost::alloc::string::String>,
    /// all, my_college
    #[prost(string, optional, tag = "4")]
    pub filter: ::core::option::Option<::prost::alloc::string::String>,
    /// latest, new, hot
    #[prost(string, optional, tag = "5")]
    pub sort: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub keyword: ::core::option::Option<::prost::alloc::string::String>,
}
/// 创建帖子请求
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreatePostRequest {
    #[prost(string, tag = "1")]
    pub board_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub content: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "5")]
    pub media: ::prost::alloc::vec::Vec<MediaItem>,
}
/// 点赞请求
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LikeRequest {
    /// like or unlike
    #[prost(string, tag = "1")]
    pub action: ::prost::alloc::string::String,
}
/// 收藏请求
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CollectRequest {
    /// collect or uncollect
    #[prost(string, tag = "1")]
    pub action: ::prost::alloc::string::String,
}
/// 创建评论请求
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateCommentRequest {
    #[prost(string, tag = "1")]
    pub content: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub reply_to_comment_id: ::core::option::Option<::prost::alloc::string::String>,
}
/// 举报请求
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReportRequest {
    /// post or comment
    #[prost(string, tag = "1")]
    pub target_type: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub target_id: ::prost::alloc::string::String,
    /// ad, politics, abuse, other
    #[prost(string, tag = "3")]
    pub reason: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "4")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
}
/// 板块列表响应
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBoardsResponse {
    #[prost(message, repeated, tag = "1")]
    pub list: ::prost::alloc::vec::Vec<Board>,
}
/// 帖子列表响应
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPostsResponse {
    #[prost(message, repeated, tag = "1")]
    pub list: ::prost::alloc::vec::Vec<PostListItem>,
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<Pagination>,
}
/// 帖子详情响应
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPostDetailResponse {
    #[prost(message, optional, tag = "1")]
    pub post: ::core::option::Option<PostDetail>,
}
/// 创建帖子响应
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreatePostResponse {
    #[prost(message, optional, tag = "1")]
    pub post: ::core::option::Option<PostDetail>,
}
/// 点赞响应
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LikeResponse {
    #[prost(int32, tag = "1")]
    pub current_like_count: i32,
    #[prost(bool, tag = "2")]
    pub is_liked: bool,
}
/// 收藏响应
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CollectResponse {
    #[prost(bool, tag = "1")]
    pub is_collected: bool,
}
/// 评论列表响应
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCommentsResponse {
    #[prost(message, repeated, tag = "1")]
    pub list: ::prost::alloc::vec::Vec<CommentDetail>,
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<Pagination>,
}
/// 创建评论响应
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateCommentResponse {
    #[prost(string, tag = "1")]
    pub comment_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub comment: ::core::option::Option<CommentDetail>,
}
/// 举报响应
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReportResponse {
    #[prost(string, tag = "1")]
    pub report_id: ::prost::alloc::string::String,
}
/// 简单成功响应
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EmptyResponse {}
