// This file is @generated by prost-build.
/// 用户信息
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserInfo {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub student_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub avatar_url: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub role: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub college: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub major: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub grade: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub class_name: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub bio: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub phone: ::prost::alloc::string::String,
    #[prost(string, tag = "12")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "13")]
    pub wechat_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "14")]
    pub weekly_course_count: i32,
    #[prost(int32, tag = "15")]
    pub forum_activity_score: i32,
    #[prost(int32, tag = "16")]
    pub collection_count: i32,
    #[prost(string, tag = "17")]
    pub setting_privacy_course: ::prost::alloc::string::String,
    #[prost(bool, tag = "18")]
    pub setting_notification_switch: bool,
}
/// 登录请求
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginRequest {
    #[prost(string, tag = "1")]
    pub student_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
}
/// 注册请求
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterRequest {
    #[prost(string, tag = "1")]
    pub student_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub college: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub major: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub phone: ::prost::alloc::string::String,
}
/// 更新资料请求
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateProfileRequest {
    #[prost(string, optional, tag = "1")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub avatar_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub bio: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub phone: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub email: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub wechat_id: ::core::option::Option<::prost::alloc::string::String>,
}
/// 修改密码请求
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChangePasswordRequest {
    #[prost(string, tag = "1")]
    pub old_password: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub new_password: ::prost::alloc::string::String,
}
/// 登录响应
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginResponse {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub user: ::core::option::Option<UserInfo>,
}
/// 注册响应
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterResponse {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
}
/// 获取用户信息响应
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserInfoResponse {
    #[prost(message, optional, tag = "1")]
    pub user: ::core::option::Option<UserInfo>,
}
/// 简单成功响应（无数据）
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EmptyResponse {}
