// This file is @generated by prost-build.
/// 分页信息
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Pagination {
    #[prost(int64, tag = "1")]
    pub total: i64,
    #[prost(int32, tag = "2")]
    pub page: i32,
    #[prost(int32, tag = "3")]
    pub page_size: i32,
    #[prost(int32, tag = "4")]
    pub pages: i32,
}
/// 学期信息
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Semester {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub start_date: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub end_date: ::prost::alloc::string::String,
    #[prost(bool, tag = "5")]
    pub is_current: bool,
}
/// 公共课程
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PublicCourse {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub course_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub teacher_name: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub teacher_id: i64,
    #[prost(string, tag = "5")]
    pub location: ::prost::alloc::string::String,
    /// 1-7: 周一到周日
    #[prost(int32, tag = "6")]
    pub day_of_week: i32,
    /// 开始节次
    #[prost(int32, tag = "7")]
    pub start_section: i32,
    /// 结束节次
    #[prost(int32, tag = "8")]
    pub end_section: i32,
    /// 上课周次列表
    #[prost(int32, repeated, tag = "9")]
    pub weeks_range: ::prost::alloc::vec::Vec<i32>,
    /// compulsory or elective
    #[prost(string, tag = "10")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(int32, tag = "11")]
    pub credits: i32,
    #[prost(string, tag = "12")]
    pub description: ::prost::alloc::string::String,
    #[prost(int32, tag = "13")]
    pub semester_id: i32,
}
/// 用户课表项
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScheduleItem {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(int64, tag = "2")]
    pub source_id: i64,
    #[prost(string, tag = "3")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "4")]
    pub semester_id: i32,
    #[prost(string, tag = "5")]
    pub course_name: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub teacher_name: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub location: ::prost::alloc::string::String,
    #[prost(int32, tag = "8")]
    pub day_of_week: i32,
    #[prost(int32, tag = "9")]
    pub start_section: i32,
    #[prost(int32, tag = "10")]
    pub end_section: i32,
    #[prost(int32, repeated, tag = "11")]
    pub weeks_range: ::prost::alloc::vec::Vec<i32>,
    #[prost(string, tag = "12")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(int32, tag = "13")]
    pub credits: i32,
    #[prost(string, tag = "14")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "15")]
    pub color_hex: ::prost::alloc::string::String,
    #[prost(bool, tag = "16")]
    pub is_custom: bool,
    #[prost(string, tag = "17")]
    pub created_at: ::prost::alloc::string::String,
}
/// 获取学期列表请求
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSemestersRequest {}
/// 获取公共课程请求
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPublicCoursesRequest {
    #[prost(int32, optional, tag = "1")]
    pub semester_id: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "2")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub teacher: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, tag = "4")]
    pub page: i32,
    #[prost(int32, tag = "5")]
    pub page_size: i32,
}
/// 获取用户课表请求
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetScheduleRequest {
    #[prost(int32, tag = "1")]
    pub semester_id: i32,
    #[prost(int32, optional, tag = "2")]
    pub week: ::core::option::Option<i32>,
}
/// 添加课表项请求（单个）
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddScheduleItemRequest {
    #[prost(int64, optional, tag = "1")]
    pub source_id: ::core::option::Option<i64>,
    #[prost(int32, tag = "2")]
    pub semester_id: i32,
    #[prost(string, tag = "3")]
    pub course_name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub teacher_name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub location: ::prost::alloc::string::String,
    #[prost(int32, tag = "6")]
    pub day_of_week: i32,
    #[prost(int32, tag = "7")]
    pub start_section: i32,
    #[prost(int32, tag = "8")]
    pub end_section: i32,
    #[prost(int32, repeated, tag = "9")]
    pub weeks: ::prost::alloc::vec::Vec<i32>,
    #[prost(string, tag = "10")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(int32, tag = "11")]
    pub credits: i32,
    #[prost(string, tag = "12")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "13")]
    pub color_hex: ::prost::alloc::string::String,
    #[prost(bool, tag = "14")]
    pub is_custom: bool,
}
/// 批量添加课表项请求
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddScheduleItemsRequest {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<AddScheduleItemRequest>,
}
/// 更新课表项请求
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateScheduleItemRequest {
    #[prost(int64, tag = "1")]
    pub item_id: i64,
    #[prost(string, optional, tag = "2")]
    pub course_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub teacher_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub location: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub color_hex: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "6")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
}
/// 删除课表项请求
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteScheduleItemRequest {
    #[prost(int64, tag = "1")]
    pub item_id: i64,
}
/// 学期列表响应
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSemestersResponse {
    #[prost(message, repeated, tag = "1")]
    pub semesters: ::prost::alloc::vec::Vec<Semester>,
}
/// 公共课程列表响应
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPublicCoursesResponse {
    #[prost(message, repeated, tag = "1")]
    pub list: ::prost::alloc::vec::Vec<PublicCourse>,
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<Pagination>,
}
/// 用户课表响应
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetScheduleResponse {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<ScheduleItem>,
}
/// 失败的项
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FailedItem {
    #[prost(string, tag = "1")]
    pub course_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub error_message: ::prost::alloc::string::String,
}
/// 批量添加课表项响应
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddScheduleItemsResponse {
    #[prost(message, repeated, tag = "1")]
    pub successful_items: ::prost::alloc::vec::Vec<ScheduleItem>,
    #[prost(message, repeated, tag = "2")]
    pub failed_items: ::prost::alloc::vec::Vec<FailedItem>,
}
/// 更新课表项响应
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateScheduleItemResponse {
    #[prost(message, optional, tag = "1")]
    pub item: ::core::option::Option<ScheduleItem>,
}
/// 简单成功响应
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EmptyResponse {}
/// 课程类型枚举
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CourseType {
    Unspecified = 0,
    /// 必修
    Compulsory = 1,
    /// 选修
    Elective = 2,
}
impl CourseType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            CourseType::Unspecified => "COURSE_TYPE_UNSPECIFIED",
            CourseType::Compulsory => "COMPULSORY",
            CourseType::Elective => "ELECTIVE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "COURSE_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "COMPULSORY" => Some(Self::Compulsory),
            "ELECTIVE" => Some(Self::Elective),
            _ => None,
        }
    }
}
