// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatMessage {
    /// system | user | assistant
    #[prost(string, tag = "1")]
    pub role: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub content: ::prost::alloc::string::String,
    /// ISO8601，可选
    #[prost(string, tag = "3")]
    pub created_at: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatUsage {
    #[prost(int32, tag = "1")]
    pub prompt_tokens: i32,
    #[prost(int32, tag = "2")]
    pub completion_tokens: i32,
    #[prost(int32, tag = "3")]
    pub total_tokens: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatRequest {
    /// 不传则新建会话
    #[prost(int64, optional, tag = "1")]
    pub conversation_id: ::core::option::Option<i64>,
    /// 需包含最新用户消息
    #[prost(message, repeated, tag = "2")]
    pub messages: ::prost::alloc::vec::Vec<ChatMessage>,
    /// 若为 true，后端可返回流式
    #[prost(bool, optional, tag = "3")]
    pub stream: ::core::option::Option<bool>,
    #[prost(double, optional, tag = "4")]
    pub temperature: ::core::option::Option<f64>,
    #[prost(int32, optional, tag = "5")]
    pub max_tokens: ::core::option::Option<i32>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatResponse {
    #[prost(int64, tag = "1")]
    pub conversation_id: i64,
    #[prost(message, optional, tag = "2")]
    pub reply: ::core::option::Option<ChatMessage>,
    #[prost(message, optional, tag = "3")]
    pub usage: ::core::option::Option<ChatUsage>,
    #[prost(string, tag = "4")]
    pub model: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub request_id: ::prost::alloc::string::String,
}
/// 流式增量（如开启 stream）
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatStreamChunk {
    #[prost(int64, tag = "1")]
    pub conversation_id: i64,
    #[prost(string, tag = "2")]
    pub delta: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub model: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub done: bool,
    #[prost(message, optional, tag = "5")]
    pub usage: ::core::option::Option<ChatUsage>,
}
/// 会话历史
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatHistoryRequest {
    #[prost(int64, tag = "1")]
    pub conversation_id: i64,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatHistoryResponse {
    #[prost(int64, tag = "1")]
    pub conversation_id: i64,
    #[prost(message, repeated, tag = "2")]
    pub messages: ::prost::alloc::vec::Vec<ChatMessage>,
    #[prost(string, tag = "3")]
    pub model: ::prost::alloc::string::String,
}
/// 会话列表（可选）
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConversationItem {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub model: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub updated_at: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListConversationsResponse {
    #[prost(message, repeated, tag = "1")]
    pub list: ::prost::alloc::vec::Vec<ConversationItem>,
}
