// Generated proto code will be included here
// The actual .rs files will be generated by prost-build during compilation

pub mod campus {
    pub mod activity {
        include!("campus.activity.rs");
    }
    
    pub mod user {
        include!("campus.user.rs");
    }
    
    pub mod forum {
        include!("campus.forum.rs");
    }
    
    pub mod course {
        include!("campus.course.rs");
    }
}

// 重新导出，方便使用
#[allow(unused_imports)]
pub use campus::activity::*;
#[allow(unused_imports)]
pub use campus::user;
#[allow(unused_imports)]
pub use campus::forum;
#[allow(unused_imports)]
pub use campus::course;
