// This file is @generated by prost-build.
/// 活动完整信息
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Activity {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub content: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub cover_url: ::prost::alloc::string::String,
    #[prost(enumeration = "ActivityType", tag = "5")]
    pub activity_type: i32,
    #[prost(string, tag = "6")]
    pub location: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub organizer: ::prost::alloc::string::String,
    /// Unix timestamp (seconds)
    #[prost(int64, tag = "8")]
    pub start_time: i64,
    #[prost(int64, tag = "9")]
    pub end_time: i64,
    #[prost(int32, tag = "10")]
    pub quota: i32,
    #[prost(int32, tag = "11")]
    pub current_enrollments: i32,
    #[prost(bool, tag = "12")]
    pub need_sign_in: bool,
    #[prost(enumeration = "ActivityStatus", tag = "13")]
    pub status: i32,
    #[prost(int64, tag = "14")]
    pub created_at: i64,
    /// 仅在详情接口返回
    #[prost(bool, optional, tag = "15")]
    pub is_enrolled: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "16")]
    pub is_collected: ::core::option::Option<bool>,
}
/// 活动列表项（精简版）
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ActivitySummary {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub cover_url: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub location: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub start_time: ::prost::alloc::string::String,
    #[prost(int32, tag = "6")]
    pub quota: i32,
    #[prost(int32, tag = "7")]
    pub current_enrollments: i32,
}
/// 报名记录
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EnrollmentRecord {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub student_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub major: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "5")]
    pub phone_number: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, tag = "6")]
    pub activity_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "7")]
    pub enroll_time: i64,
    #[prost(enumeration = "AttendanceStatus", tag = "8")]
    pub attendance_status: i32,
}
/// 我的报名活动项
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EnrollmentSummary {
    #[prost(string, tag = "1")]
    pub activity_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub cover_url: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub start_time: i64,
    #[prost(int64, tag = "5")]
    pub end_time: i64,
    #[prost(enumeration = "EnrollmentStatus", tag = "6")]
    pub my_status: i32,
}
/// 我的收藏活动项
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CollectionSummary {
    #[prost(string, tag = "1")]
    pub activity_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub cover_url: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub start_time: i64,
    #[prost(int64, tag = "5")]
    pub end_time: i64,
}
/// 管理员发布活动
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateActivityRequest {
    #[prost(string, tag = "1")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub content: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub location: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub organizer: ::prost::alloc::string::String,
    #[prost(int64, tag = "5")]
    pub start_time: i64,
    #[prost(int64, tag = "6")]
    pub end_time: i64,
    #[prost(string, optional, tag = "7")]
    pub cover_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "ActivityType", optional, tag = "8")]
    pub activity_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "9")]
    pub quota: ::core::option::Option<i32>,
    #[prost(bool, optional, tag = "10")]
    pub need_sign_in: ::core::option::Option<bool>,
}
/// 修改活动
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateActivityRequest {
    #[prost(string, tag = "1")]
    pub activity_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub title: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub content: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub cover_url: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "ActivityType", optional, tag = "5")]
    pub activity_type: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "6")]
    pub location: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "7")]
    pub organizer: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int64, optional, tag = "8")]
    pub start_time: ::core::option::Option<i64>,
    #[prost(int64, optional, tag = "9")]
    pub end_time: ::core::option::Option<i64>,
    #[prost(int32, optional, tag = "10")]
    pub quota: ::core::option::Option<i32>,
    #[prost(bool, optional, tag = "11")]
    pub need_sign_in: ::core::option::Option<bool>,
    #[prost(enumeration = "ActivityStatus", optional, tag = "12")]
    pub status: ::core::option::Option<i32>,
}
/// 获取活动列表
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetActivitiesRequest {
    #[prost(string, optional, tag = "1")]
    pub keyword: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(enumeration = "ActivityType", optional, tag = "2")]
    pub activity_type: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "3")]
    pub page: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "4")]
    pub page_size: ::core::option::Option<i32>,
}
/// 获取活动详情
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetActivityDetailRequest {
    #[prost(string, tag = "1")]
    pub activity_id: ::prost::alloc::string::String,
}
/// 学生报名
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EnrollActivityRequest {
    #[prost(string, tag = "1")]
    pub activity_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub student_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub major: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "5")]
    pub phone_number: ::core::option::Option<::prost::alloc::string::String>,
}
/// 取消报名
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CancelEnrollmentRequest {
    #[prost(string, tag = "1")]
    pub activity_id: ::prost::alloc::string::String,
}
/// 收藏活动
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CollectActivityRequest {
    #[prost(string, tag = "1")]
    pub activity_id: ::prost::alloc::string::String,
}
/// 取消收藏
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UncollectActivityRequest {
    #[prost(string, tag = "1")]
    pub activity_id: ::prost::alloc::string::String,
}
/// 获取报名列表
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetEnrollmentsRequest {
    #[prost(string, tag = "1")]
    pub activity_id: ::prost::alloc::string::String,
}
/// 我的活动
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetMyActivitiesRequest {
    #[prost(bool, optional, tag = "1")]
    pub include_enrollments: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "2")]
    pub include_collections: ::core::option::Option<bool>,
    #[prost(int32, optional, tag = "3")]
    pub page: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "4")]
    pub page_size: ::core::option::Option<i32>,
}
/// 管理员发布活动响应
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateActivityResponse {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub data: ::prost::alloc::vec::Vec<Activity>,
}
/// 修改活动响应
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateActivityResponse {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// null
    #[prost(string, optional, tag = "3")]
    pub data: ::core::option::Option<::prost::alloc::string::String>,
}
/// 获取活动列表响应
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetActivitiesResponse {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub data: ::core::option::Option<GetActivitiesData>,
}
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetActivitiesData {
    #[prost(message, repeated, tag = "1")]
    pub list: ::prost::alloc::vec::Vec<ActivitySummary>,
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<super::common::Pagination>,
}
/// 获取活动详情响应
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetActivityDetailResponse {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub data: ::core::option::Option<Activity>,
}
/// 学生报名响应
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EnrollActivityResponse {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// null
    #[prost(string, optional, tag = "3")]
    pub data: ::core::option::Option<::prost::alloc::string::String>,
}
/// 取消报名响应
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CancelEnrollmentResponse {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// null
    #[prost(string, optional, tag = "3")]
    pub data: ::core::option::Option<::prost::alloc::string::String>,
}
/// 收藏活动响应
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CollectActivityResponse {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// null
    #[prost(string, optional, tag = "3")]
    pub data: ::core::option::Option<::prost::alloc::string::String>,
}
/// 取消收藏响应
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UncollectActivityResponse {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// null
    #[prost(string, optional, tag = "3")]
    pub data: ::core::option::Option<::prost::alloc::string::String>,
}
/// 获取报名列表响应
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetEnrollmentsResponse {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub data: ::core::option::Option<GetEnrollmentsData>,
}
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetEnrollmentsData {
    #[prost(int32, tag = "1")]
    pub total_enrolled: i32,
    #[prost(message, repeated, tag = "2")]
    pub enrollment_list: ::prost::alloc::vec::Vec<EnrollmentRecord>,
}
/// 我的活动响应
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMyActivitiesResponse {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub data: ::core::option::Option<GetMyActivitiesData>,
}
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMyActivitiesData {
    #[prost(message, optional, tag = "1")]
    pub enrolled_data: ::core::option::Option<EnrolledData>,
    #[prost(message, optional, tag = "2")]
    pub collected_data: ::core::option::Option<CollectedData>,
}
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnrolledData {
    #[prost(message, optional, tag = "1")]
    pub pagination: ::core::option::Option<super::common::Pagination>,
    #[prost(message, repeated, tag = "2")]
    pub list: ::prost::alloc::vec::Vec<EnrollmentSummary>,
}
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CollectedData {
    #[prost(message, optional, tag = "1")]
    pub pagination: ::core::option::Option<super::common::Pagination>,
    #[prost(message, repeated, tag = "2")]
    pub list: ::prost::alloc::vec::Vec<CollectionSummary>,
}
/// 活动类型
#[derive(uniffi::Enum, serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ActivityType {
    Unknown = 0,
    /// 讲座
    Lecture = 1,
    /// 社团
    Club = 2,
    /// 竞赛
    Competition = 3,
}
impl ActivityType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "ACTIVITY_TYPE_UNKNOWN",
            Self::Lecture => "ACTIVITY_TYPE_LECTURE",
            Self::Club => "ACTIVITY_TYPE_CLUB",
            Self::Competition => "ACTIVITY_TYPE_COMPETITION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ACTIVITY_TYPE_UNKNOWN" => Some(Self::Unknown),
            "ACTIVITY_TYPE_LECTURE" => Some(Self::Lecture),
            "ACTIVITY_TYPE_CLUB" => Some(Self::Club),
            "ACTIVITY_TYPE_COMPETITION" => Some(Self::Competition),
            _ => None,
        }
    }
}
/// 活动状态
#[derive(uniffi::Enum, serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ActivityStatus {
    Unknown = 0,
    /// 已发布/进行中
    Published = 1,
    /// 已结束
    Finished = 2,
    /// 已撤销
    Cancelled = 3,
}
impl ActivityStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "ACTIVITY_STATUS_UNKNOWN",
            Self::Published => "ACTIVITY_STATUS_PUBLISHED",
            Self::Finished => "ACTIVITY_STATUS_FINISHED",
            Self::Cancelled => "ACTIVITY_STATUS_CANCELLED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ACTIVITY_STATUS_UNKNOWN" => Some(Self::Unknown),
            "ACTIVITY_STATUS_PUBLISHED" => Some(Self::Published),
            "ACTIVITY_STATUS_FINISHED" => Some(Self::Finished),
            "ACTIVITY_STATUS_CANCELLED" => Some(Self::Cancelled),
            _ => None,
        }
    }
}
/// 签到状态
#[derive(uniffi::Enum, serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AttendanceStatus {
    Unknown = 0,
    /// 未签到
    NotSigned = 1,
    /// 已签到
    Signed = 2,
}
impl AttendanceStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "ATTENDANCE_STATUS_UNKNOWN",
            Self::NotSigned => "ATTENDANCE_STATUS_NOT_SIGNED",
            Self::Signed => "ATTENDANCE_STATUS_SIGNED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ATTENDANCE_STATUS_UNKNOWN" => Some(Self::Unknown),
            "ATTENDANCE_STATUS_NOT_SIGNED" => Some(Self::NotSigned),
            "ATTENDANCE_STATUS_SIGNED" => Some(Self::Signed),
            _ => None,
        }
    }
}
/// 报名状态
#[derive(uniffi::Enum, serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EnrollmentStatus {
    Unknown = 0,
    /// 已报名
    Enrolled = 1,
    /// 已取消报名
    Cancelled = 2,
}
impl EnrollmentStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "ENROLLMENT_STATUS_UNKNOWN",
            Self::Enrolled => "ENROLLMENT_STATUS_ENROLLED",
            Self::Cancelled => "ENROLLMENT_STATUS_CANCELLED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ENROLLMENT_STATUS_UNKNOWN" => Some(Self::Unknown),
            "ENROLLMENT_STATUS_ENROLLED" => Some(Self::Enrolled),
            "ENROLLMENT_STATUS_CANCELLED" => Some(Self::Cancelled),
            _ => None,
        }
    }
}
