// This file is @generated by prost-build.
/// 分页信息
#[derive(uniffi::Record)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Pagination {
    #[prost(int64, tag = "1")]
    pub total: i64,
    #[prost(int32, tag = "2")]
    pub page: i32,
    #[prost(int32, tag = "3")]
    pub page_size: i32,
    #[prost(int32, tag = "4")]
    pub pages: i32,
}
