// This file is @generated by prost-build.
/// 学期信息
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Semester {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// YYYY-MM-DD
    #[prost(string, tag = "3")]
    pub start_date: ::prost::alloc::string::String,
    /// YYYY-MM-DD
    #[prost(string, tag = "4")]
    pub end_date: ::prost::alloc::string::String,
    #[prost(bool, tag = "5")]
    pub is_current: bool,
}
/// 全校课程
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PublicCourse {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub course_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub teacher_name: ::prost::alloc::string::String,
    #[prost(int64, optional, tag = "4")]
    pub teacher_id: ::core::option::Option<i64>,
    #[prost(string, tag = "5")]
    pub location: ::prost::alloc::string::String,
    /// 1-7 (1代表周一)
    #[prost(int32, tag = "6")]
    pub day_of_week: i32,
    #[prost(int32, tag = "7")]
    pub start_section: i32,
    #[prost(int32, tag = "8")]
    pub end_section: i32,
    #[prost(int32, repeated, tag = "9")]
    pub weeks_range: ::prost::alloc::vec::Vec<i32>,
    /// "compulsory" 或 "elective"
    #[prost(string, tag = "10")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(int32, tag = "11")]
    pub credits: i32,
    #[prost(string, optional, tag = "12")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
}
/// 用户课表项
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ScheduleItem {
    #[prost(int64, tag = "1")]
    pub id: i64,
    /// 关联的全校课程ID
    #[prost(int64, optional, tag = "2")]
    pub source_id: ::core::option::Option<i64>,
    #[prost(string, tag = "3")]
    pub course_name: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "4")]
    pub teacher_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub location: ::core::option::Option<::prost::alloc::string::String>,
    /// 1-7 (1代表周一)
    #[prost(int32, tag = "6")]
    pub day_of_week: i32,
    #[prost(int32, tag = "7")]
    pub start_section: i32,
    #[prost(int32, tag = "8")]
    pub end_section: i32,
    #[prost(int32, repeated, tag = "9")]
    pub weeks: ::prost::alloc::vec::Vec<i32>,
    /// "compulsory" 或 "elective"
    #[prost(string, optional, tag = "10")]
    pub r#type: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "11")]
    pub credits: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "12")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    /// #RRGGBB 格式
    #[prost(string, tag = "13")]
    pub color_hex: ::prost::alloc::string::String,
    #[prost(bool, tag = "14")]
    pub is_custom: bool,
}
/// 批量添加失败项
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FailedItem {
    #[prost(string, tag = "1")]
    pub course_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub error_message: ::prost::alloc::string::String,
}
/// 获取学期列表请求
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSemestersRequest {}
/// 获取全校课程列表请求
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPublicCoursesRequest {
    #[prost(int64, optional, tag = "1")]
    pub semester_id: ::core::option::Option<i64>,
    /// 课程名称模糊搜索
    #[prost(string, optional, tag = "2")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    /// 教师姓名模糊搜索
    #[prost(string, optional, tag = "3")]
    pub teacher: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, tag = "4")]
    pub page: i32,
    #[prost(int32, tag = "5")]
    pub page_size: i32,
}
/// 获取用户课表请求
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetScheduleRequest {
    #[prost(int64, tag = "1")]
    pub semester_id: i64,
    /// 筛选指定周
    #[prost(int32, optional, tag = "2")]
    pub week: ::core::option::Option<i32>,
}
/// 添加课表项请求
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddScheduleItemsRequest {
    #[prost(int64, tag = "1")]
    pub semester_id: i64,
    #[prost(message, repeated, tag = "2")]
    pub items: ::prost::alloc::vec::Vec<ScheduleItemInput>,
}
/// 添加课表项输入
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ScheduleItemInput {
    /// 关联的全校课程ID
    #[prost(int64, optional, tag = "1")]
    pub source_id: ::core::option::Option<i64>,
    #[prost(string, tag = "2")]
    pub course_name: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "3")]
    pub teacher_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub location: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, tag = "5")]
    pub day_of_week: i32,
    #[prost(int32, tag = "6")]
    pub start_section: i32,
    #[prost(int32, tag = "7")]
    pub end_section: i32,
    #[prost(int32, repeated, tag = "8")]
    pub weeks: ::prost::alloc::vec::Vec<i32>,
    #[prost(string, optional, tag = "9")]
    pub r#type: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "10")]
    pub credits: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "11")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    /// #RRGGBB 格式
    #[prost(string, tag = "12")]
    pub color_hex: ::prost::alloc::string::String,
    #[prost(bool, tag = "13")]
    pub is_custom: bool,
}
/// 更新课表项请求
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateScheduleItemRequest {
    #[prost(int64, tag = "1")]
    pub item_id: i64,
    #[prost(string, optional, tag = "2")]
    pub course_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub teacher_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "4")]
    pub location: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "5")]
    pub day_of_week: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "6")]
    pub start_section: ::core::option::Option<i32>,
    #[prost(int32, optional, tag = "7")]
    pub end_section: ::core::option::Option<i32>,
    #[prost(int32, repeated, tag = "8")]
    pub weeks: ::prost::alloc::vec::Vec<i32>,
    #[prost(string, optional, tag = "9")]
    pub r#type: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "10")]
    pub credits: ::core::option::Option<i32>,
    #[prost(string, optional, tag = "11")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "12")]
    pub color_hex: ::core::option::Option<::prost::alloc::string::String>,
}
/// 删除课表项请求
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteScheduleItemRequest {
    #[prost(int64, tag = "1")]
    pub item_id: i64,
}
/// 获取学期列表响应
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSemestersResponse {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub data: ::core::option::Option<GetSemestersData>,
}
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSemestersData {
    #[prost(message, repeated, tag = "1")]
    pub semesters: ::prost::alloc::vec::Vec<Semester>,
}
/// 获取全校课程列表响应
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPublicCoursesResponse {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub data: ::core::option::Option<GetPublicCoursesData>,
}
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPublicCoursesData {
    #[prost(message, repeated, tag = "1")]
    pub list: ::prost::alloc::vec::Vec<PublicCourse>,
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<super::common::Pagination>,
}
/// 获取用户课表响应
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetScheduleResponse {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub data: ::core::option::Option<GetScheduleData>,
}
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetScheduleData {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<ScheduleItem>,
}
/// 添加课表项响应
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddScheduleItemsResponse {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub data: ::core::option::Option<AddScheduleItemsData>,
}
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddScheduleItemsData {
    #[prost(message, repeated, tag = "1")]
    pub successful_items: ::prost::alloc::vec::Vec<ScheduleItem>,
    #[prost(message, repeated, tag = "2")]
    pub failed_items: ::prost::alloc::vec::Vec<FailedItem>,
}
/// 更新课表项响应
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateScheduleItemResponse {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub data: ::core::option::Option<UpdateScheduleItemData>,
}
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateScheduleItemData {
    #[prost(message, optional, tag = "1")]
    pub item: ::core::option::Option<ScheduleItem>,
}
/// 删除课表项响应
#[derive(uniffi::Record, serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteScheduleItemResponse {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
