// This file is @generated by prost-build.
/// 文件上传结果
#[derive(
    uniffi::Record,
    serde::Serialize,
    serde::Deserialize,
    Clone,
    PartialEq,
    Eq,
    Hash,
    ::prost::Message,
)]
pub struct UploadResult {
    /// 文件在对象存储中的永久访问链接 (OSS URL)
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
    /// 如果是图片，返回自动生成的缩略图 URL (可选)
    #[prost(string, optional, tag = "2")]
    pub thumbnail_url: ::core::option::Option<::prost::alloc::string::String>,
    /// 服务器保存的文件名
    #[prost(string, tag = "3")]
    pub filename: ::prost::alloc::string::String,
    /// 文件大小，单位：字节 (Bytes)
    #[prost(int64, tag = "4")]
    pub size: i64,
}
/// 文件上传请求
#[derive(
    uniffi::Record,
    serde::Serialize,
    serde::Deserialize,
    Clone,
    PartialEq,
    Eq,
    Hash,
    ::prost::Message,
)]
pub struct UploadFileRequest {
    /// 文件二进制数据
    #[prost(bytes = "vec", tag = "1")]
    pub file: ::prost::alloc::vec::Vec<u8>,
    /// 文件类型提示 (可选，服务端会自动检测)
    #[prost(string, optional, tag = "2")]
    pub file_type: ::core::option::Option<::prost::alloc::string::String>,
}
/// 文件上传响应
#[derive(
    uniffi::Record,
    serde::Serialize,
    serde::Deserialize,
    Clone,
    PartialEq,
    Eq,
    Hash,
    ::prost::Message,
)]
pub struct UploadFileResponse {
    /// 业务状态码，通常200表示成功
    #[prost(int32, tag = "1")]
    pub code: i32,
    /// 状态信息，对code的简要描述
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// 业务数据主体
    #[prost(message, optional, tag = "3")]
    pub data: ::core::option::Option<UploadResult>,
}
