// This file is @generated by prost-build.
/// 用户信息
#[derive(uniffi::Record)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct User {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(string, tag = "2")]
    pub student_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    /// 头像
    #[prost(string, tag = "4")]
    pub avatar_url: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub role: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub college: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub major: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub grade: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub class_name: ::prost::alloc::string::String,
    /// 简介
    #[prost(string, tag = "10")]
    pub bio: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub phone: ::prost::alloc::string::String,
    #[prost(string, tag = "12")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "13")]
    pub wechat_id: ::prost::alloc::string::String,
    /// 本周课时数
    #[prost(int32, tag = "14")]
    pub weekly_course_count: i32,
    /// 论坛活跃度
    #[prost(int32, tag = "15")]
    pub forum_activity_score: i32,
    /// 收藏数
    #[prost(int32, tag = "16")]
    pub collection_count: i32,
    /// 课表隐私
    #[prost(string, tag = "17")]
    pub setting_privacy_course: ::prost::alloc::string::String,
    /// 通知开关
    #[prost(bool, tag = "18")]
    pub setting_notification_switch: bool,
}
/// 登录成功返回数据
#[derive(uniffi::Record)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginData {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub user: ::core::option::Option<User>,
}
/// 注册成功返回数据
#[derive(uniffi::Record)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterData {
    #[prost(int64, tag = "1")]
    pub user_id: i64,
}
/// 批量注册成功项
#[derive(uniffi::Record)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ImportSuccessItem {
    /// 行号
    #[prost(int32, tag = "1")]
    pub row: i32,
    /// 学号
    #[prost(string, tag = "2")]
    pub student_id: ::prost::alloc::string::String,
    /// 姓名
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    /// 状态
    #[prost(string, tag = "4")]
    pub status: ::prost::alloc::string::String,
    /// 自动生成密码
    #[prost(string, tag = "5")]
    pub initial_password: ::prost::alloc::string::String,
    /// 是否发送邮件
    #[prost(bool, tag = "6")]
    pub email_sent: bool,
}
/// 批量注册失败项
#[derive(uniffi::Record)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ImportFailedItem {
    /// 行号
    #[prost(int32, tag = "1")]
    pub row: i32,
    /// 学号
    #[prost(string, tag = "2")]
    pub student_id: ::prost::alloc::string::String,
    /// 姓名
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    /// 错误信息
    #[prost(string, tag = "4")]
    pub error: ::prost::alloc::string::String,
    /// 状态
    #[prost(string, tag = "5")]
    pub status: ::prost::alloc::string::String,
}
/// 批量注册详情
#[derive(uniffi::Record)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ImportDetails {
    /// 成功列表
    #[prost(message, repeated, tag = "1")]
    pub success_list: ::prost::alloc::vec::Vec<ImportSuccessItem>,
    /// 失败列表
    #[prost(message, repeated, tag = "2")]
    pub failed_list: ::prost::alloc::vec::Vec<ImportFailedItem>,
}
/// 批量注册返回数据
#[derive(uniffi::Record)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ImportData {
    /// 成功数量
    #[prost(int32, tag = "1")]
    pub success_count: i32,
    /// 失败数量
    #[prost(int32, tag = "2")]
    pub failed_count: i32,
    /// 总数量
    #[prost(int32, tag = "3")]
    pub total_count: i32,
    /// 文件名
    #[prost(string, tag = "4")]
    pub file_name: ::prost::alloc::string::String,
    /// 导入时间
    #[prost(string, tag = "5")]
    pub import_time: ::prost::alloc::string::String,
    /// 详情
    #[prost(message, optional, tag = "6")]
    pub details: ::core::option::Option<ImportDetails>,
}
/// 用户登录请求
#[derive(uniffi::Record)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginRequest {
    #[prost(string, tag = "1")]
    pub student_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
}
/// 用户注册请求
#[derive(uniffi::Record)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterRequest {
    #[prost(string, tag = "1")]
    pub student_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub college: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub major: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub phone: ::prost::alloc::string::String,
}
/// 获取当前用户信息请求
///
/// 该请求不需要请求参数，通过Token识别用户
#[derive(uniffi::Record)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUserInfoRequest {}
/// 更新个人资料请求
#[derive(uniffi::Record)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateProfileRequest {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub avatar_url: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub bio: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub phone: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub wechat_id: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub setting_privacy_course: ::prost::alloc::string::String,
    #[prost(bool, tag = "8")]
    pub setting_notification_switch: bool,
}
/// 退出登录请求
///
/// 该请求不需要请求参数，通过Token识别用户
#[derive(uniffi::Record)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogoutRequest {}
/// 修改密码请求
#[derive(uniffi::Record)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChangePasswordRequest {
    /// 旧密码
    #[prost(string, tag = "1")]
    pub old_password: ::prost::alloc::string::String,
    /// 新密码
    #[prost(string, tag = "2")]
    pub new_password: ::prost::alloc::string::String,
}
/// 批量注册请求
#[derive(uniffi::Record)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BatchRegisterRequest {
    /// Excel/CSV格式的用户数据文件
    #[prost(bytes = "vec", tag = "1")]
    pub file: ::prost::alloc::vec::Vec<u8>,
    /// 文件名
    #[prost(string, tag = "2")]
    pub file_name: ::prost::alloc::string::String,
}
/// 删除账号请求
#[derive(uniffi::Record)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteUserRequest {
    /// 用户ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
/// 用户登录响应
#[derive(uniffi::Record)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginResponse {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub data: ::core::option::Option<LoginData>,
}
/// 用户注册响应
#[derive(uniffi::Record)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterResponse {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub data: ::core::option::Option<RegisterData>,
}
/// 获取当前用户信息响应
#[derive(uniffi::Record)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUserInfoResponse {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub data: ::core::option::Option<User>,
}
/// 更新个人资料响应
#[derive(uniffi::Record)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateProfileResponse {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// 退出登录响应
#[derive(uniffi::Record)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LogoutResponse {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// 修改密码响应
#[derive(uniffi::Record)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChangePasswordResponse {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// 批量注册响应
#[derive(uniffi::Record)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BatchRegisterResponse {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// 批量注册结果数据
    #[prost(message, optional, tag = "3")]
    pub data: ::core::option::Option<ImportData>,
}
/// 删除账号响应
#[derive(uniffi::Record)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteUserResponse {
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
